#include <iostream>
#include <string>

using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long M){
    if(N==M)
        cout<<YES<<endl;
    else
    {
        cout<<NO<<endl;
    }
    return;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    solve(N, M);
    return 0;
}
