/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author houghstc
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <vector>
#include <deque>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <queue>
#include <stack>
#include <string>
#include <algorithm>
#include <cstring>
#include <climits>

using namespace std;
using pii = pair<int, int>;
using ll = long long;
using pll = pair<ll, ll>;

const int MOD = 1e9+7;

class CSumOfProductOfPairs {
public:
    void solve(std::istream& in, std::ostream& out) {
        int n;
        in >> n;
        ll pre;
        in >> pre;
        ll res = 0;
        for(int i = 2; i <= n; ++i)
        {
            ll a;
            in >> a;
            res = (res + a * pre) % MOD;
            pre += a;
            pre %= MOD;
        }
        out << res << endl;
    }
};


int main() {
    ios::sync_with_stdio(false);
    cin.tie(NULL);
    CSumOfProductOfPairs solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
