#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long N, std::vector<long long> A){
    vector<long long> s(N + 1);
    for (int i = N - 1; i >= 0; i--) {
        s[i] = (s[i + 1] + A[i]) % MOD;
    }
    long long ans = 0;
    for (int i = 0; i < N - 1; i++) {
        ans += (A[i] * s[i + 1]);
        ans %= MOD;
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
