/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define MOD 1000000007
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))

class CSumOfProductOfPairs {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    vector<int> a(n);
    REP(i,n) in >> a[i];
    int sub_sum = 0;
    FOR(i,1,n){
      sub_sum += a[i];
    }
    int ans = 0;
    REP(i,n-1){
      ans += (a[i] % MOD) * (sub_sum % MOD);
      ans %= MOD;
      sub_sum -= a[i+1];
    }
    out << ans << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CSumOfProductOfPairs solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
