#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <queue>
#include <iostream>
#include <cmath>

#define REP(i,n) for(ll i=0;i<(ll)(n);i++)
#define REPD(i,n) for(ll i=n-1;i>=0;i--)
#define FOR(i,a,b) for(ll i=a;i<=(ll)(b);i++)
#define FORD(i,a,b) for(ll i=a;i>=(ll)(b);i--)
typedef long long ll;
using namespace std;

const long long MOD = 1000000007;

void solve(long long N, std::vector<long long> A){
    long long res = 0;
    vector<long long> B(N);
    fill(B.begin(), B.end(), 0);

    B[N-1] = A[N-1];
    for(int i = N-2; i >= 0; i--) {
        B[i] += (B[i+1] + A[i]) % MOD;
    }
    // REP(i, N) cout << "," << B[i];
    // cout << endl;
    
    REP(i, N-1) { 
        res += (A[i] * B[i+1])  % MOD;
    }
    
    cout << res % MOD << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
