/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define pb push_back
#define mp make_pair
#define mod1 1000000007
#define mod2 1000000009
int getTheAnswer() {
    return 42;
}

using namespace std;
using ll=long long;

class CSumOfProductOfPairs {
public:
	void solve(std::istream& cin, std::ostream& cout) {
        ll n;
        cin>>n;
        ll a[n],b[n];
        for (int i=0;i<n;i++)
            cin>>a[i];
        b[n-1]=a[n-1];
        for (int i=n-2;i>=0;i--){
            b[i]=a[i]+b[i+1];
            b[i]%=mod1;
        }
        ll sum=0;
        for (int i=0;i<n-1;i++){
            sum+=((a[i]%mod1)*(b[i+1]%mod1))%mod1;
            sum%=mod1;
        }
        cout<<sum;
	}
};


int main() {
	CSumOfProductOfPairs solver;
	std::ios::sync_with_stdio(false);
	std::cin.tie(NULL);
	std::cout.tie(NULL);
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
