/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author P.Alizadeh
 */

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;

typedef long long int   ll;
typedef long double     ld;
typedef pair<ll,ll>     pll;
typedef complex<ld>     cld;

#define all(x)          x.begin(),x.end()
#define Sort(x)         sort(all(x))
#define kill(x)         return cout << x << endl, 0;
#define Mp              make_pair
#define X               first
#define Y               second
#define sep             " "
#define endl            "\n"
#define fastio          ios_base::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define file_io         freopen("in.txt" , "r" , stdin) ; freopen("out.txt" , "w" , stdout);
#define ld_io           cout << setprecision(10) << fixed;
mt19937 rng(chrono::steady_clock::now().time_since_epoch().count());

ll pw(ll a, ll b, ll md) {
    if (!b)
        return 1;
    if (b & 1)
        return a * pw(a * a % md, b / 2, md) % md;
    return pw(a * a % md, b / 2, md) % md;
}

ll inmod(ll a, ll m) {
    a = (-m < a && a < m) ? a : a % m;
    if (a < 0)  a += m;
    return a;
}

const ll MAXN = 1e5 + 10,
         INF  = 8e18,
         MOD  = 1e9 + 7,
         LOG  = 32;
//const ld PI   = M_PI;

ll n, d, a[MAXN], dp[MAXN][110], x;
string s;

int main()
{
    fastio;
    //ld_io;

    cin >> s >> d;
    n = s.size();
    for (ll i = 0; i < n; i++)
        a[i + 1] = s[i] - '0';

    for (ll i = 0; i <= a[1]; i++)
        dp[1][i % d]++;
    x = a[1] % d;

    for (ll i = 2; i <= n; i++) {
        for (ll j = 0; j < d; j++) {
            for (ll k = 0; k < 10; k++) {
                ll p = inmod(j - k, d);
                if (p == x && k > a[i])
                    dp[i][j] += dp[i - 1][p] - 1 + MOD;
                else
                    dp[i][j] += dp[i - 1][p];
                dp[i][j] %= MOD;
            }
        }
        x = (x + a[i]) % d;
    }

    cout << (dp[n][0] - 1 + MOD) % MOD << endl;

    return 0;
}

