/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author aps
 */

#include "bits/stdc++.h"

using namespace std;

#define int long long int
#define all(x) x.begin(), x.end()
#define pb push_back
#define mp make_pair
#define se second
#define fi first

typedef pair<int, int> pii;
typedef vector<int> vi;

const int inf = 1e18;
const int mod = 1e9+7;

inline int add(int x, int y) { x += y; if (x >= mod) x -= mod; return x;}
inline int sub(int x, int y) { x -= y; if (x < 0) x += mod; return x;}
inline int mul(int x, int y) { return ((x % mod) * (y % mod)) % mod;}
inline int power(int a, int b) {
    int x = 1;
    while (b) {
        if (b & 1) x = mul(x, a);
        a = mul(a, a);
        b >>= 1;
    }
    return x;
}
inline int inv(int a) { return power(a, mod - 2);}

int dp[100005][105][2];

class SDigitSum {
public:
    void solve(std::istream& cin, std::ostream& cout){
        string s; cin >> s;
        int n = s.length();
        int d; cin >> d;

        memset(dp,0,sizeof dp);
        dp[0][0][0] = 1;
        for(int i=0;i<n;i++){
            for(int j=0;j<d;j++){
                for(int k=0;k<2;k++){
                    int r=9;
                    if(k==0) r=s[i]-'0';
                    for(int cd=0;cd<=r;cd++){
                        int ck=k;
                        if(cd < s[i]-'0') ck=1;
                        dp[i+1][(j+cd)%d][ck] = add(dp[i+1][(j+cd)%d][ck],dp[i][j][k]);
                    }
                }
            }
        }

        //cout << dp[n][0][0] << " " << dp[n][0][1] << endl;
        int ans = add(dp[n][0][0],dp[n][0][1]);
        ans = sub(ans,1LL);
        cout << ans << endl;
    }
};


int32_t main() {
    ios_base::sync_with_stdio(false); cin.tie(nullptr); cout.tie(nullptr);
    SDigitSum solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
