/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Gosu_Hiroo
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

#ifdef int
#define V2(v,size_1, size_2, value) vector<vector<long long>>v(size_1, vector<long long>(size_2, value))
#define V3(v,size_1,size_2,size_3,value) vector<vector<vector<long long>>>v(size_1,vector<vector<long long>>(size_2,vector<long long>(size_1, value)))
#define VI vector<long long>
#define G(g,size_1) vector<vector<long long>>g(size_1, vector<long long>())
#define SZ(x) ((long long)(x).size())
#define VVI  vector<vector<long long>>
#define VVVI  vector<vector<vector<long long>>>
#define SZ(x) ((long long)(x).size())
#define READ ({long long t;cin >> t;t;})
#define PII pair<long long, long long>
#else
#define V2(v,size_1, size_2, value) vector<vector<int>>v(size_1, vector<int>(size_2, value))
#define V3(v,size_1,size_2,size_3,value) vector<vector<vector<int>>>v(size_1,vector<vector<int>>(size_2,vector<int>(size_1, value)))
#define VI vector<int>
#define G(g,size_1) vector<vector<int>>g(size_1, vector<int>())
#define SZ(x) ((int)(x).size())
#define VVI  vector<vector<int>>
#define VVVI  vector<vector<vector<int>>>
#define SZ(x) ((int)(x).size())
#define READ ({int t;cin >> t;t;})
#define PII pair<int, int>
#endif

#define VM2(v,size_1, size_2, value) vector<vector<mint>>v(size_1, vector<mint>(size_2, value))
#define VM3(v,size_1,size_2,size_3,value) vector<vector<vector<mint>>>v(size_1,vector<vector<mint>>(size_2,vector<mint>(size_1, value)))
#define VM   vector<mint>
#define VVM  vector<vector<mint>>
#define VVVM  vector<vector<vector<mint>>>

#define TR(container, it) \
        for (auto it = container.begin(); it != container.end(); it++)
#define IN(c, x) ((c).find(x) != (c).end())   //O(log n)
#define IN_L(c, x) (find((c).begin(),(c).end(),x) != (c).end()) //O(n)
#define FOR(i, _begin, _end) for (__typeof(_end) end = _end, begin = _begin,  i = (begin) - ((begin) > (end)); i != (end) - ((begin) > (end)); i += 1 - 2 * ((begin) > (end)))
#define REP(i, end) for (__typeof(end) i = 0, _len = (end); i < (_len); i += 1)
#define ALL(x) (x).begin(),(x).end()
#define F first
#define S second
#define y0 y3487465
#define y1 y8687969
#define j0 j1347829
#define j1 j234892
#define MOD(x, m) ((((x) % (m)) + (m)) % (m))
#define BIT(n) (1LL<<(n))
#define UNIQUE(v) v.erase( unique(v.begin(), v.end()), v.end() );
#define EB emplace_back
#define PB push_back
#define fcout cout << fixed << setprecision(12)
#define fcerr cerr << fixed << setprecision(12)
#define print(x) cout << (x) << endl
# define BYE(a) do { cout << (a) << endl; return ; } while (false)

#ifdef DEBUG
#define ERR(args...) { string _s = #args; replace(_s.begin(), _s.end(), ',', ' '); stringstream _ss(_s); istream_iterator<string> _it(_ss); _err(cerr,_it, args); }
#define DBG(x) cerr << #x << " is " << x << endl;
#else
#define DBG(x) {};
#define ERR(args...) {};
#endif
void _err(std::ostream& cerr,istream_iterator<string> it) {cerr << endl;}
template<typename T, typename... Args>
void _err(std::ostream& cerr, istream_iterator<string> it, T a, Args... args) {
    cerr << *it << " = " << a << "  ";
    _err(cerr,++it, args...);
}

const double pi = 2 * acos(.0);
const int inf = 0x3f3f3f3f;
const ll mod = (ll) (1e9) + 7;
//const ll mod = (ll) 998244353 ;
const double eps = 1e-10;

template<typename A, size_t N, typename T>
void Fill(A (&array)[N], const T &val) {
    std::fill((T *) array, (T *) (array + N), val);
}


template <typename T>
ostream& operator << (ostream& os, const vector<T> V) {
    os << "[";
    int cnt = 0;
    T curr;
    if(!V.empty()){
        for (int i = 0; i < V.size() - 1; ++i) {
            if(V[i] == curr)cnt ++;
            else cnt = 0;
            if(cnt == 4)os << "... ";
            if(cnt < 4)
                os << V[i] << " ";
            curr = V[i];
        }
        os << V.back();
    }
    os << "]";
    return os;
}

template <typename T, typename U>
ostream& operator << (ostream& os, const pair<T,U> P) {
    os << "(";
    os << P.first << "," << P.second;
    os << ")";
    return os;
}

template <typename T, typename U>
ostream& operator << (ostream& os, const set<T,U> V) {
    os << "{";
    if(!V.empty()){
        auto it = V.begin();
        for (int i = 0; i < V.size() -1; ++i) {
            os << *it << " ";
            it++;
        }
        os << *it;
    }
    os << "}";
    return os;
}

template <typename K, typename H, typename P>
ostream& operator << (ostream& os, const unordered_set<K, H, P> V) {
    os << "{";
    if(!V.empty()){
        auto it = V.begin();
        for (int i = 0; i < V.size() -1; ++i) {
            os << *it << " ";
            it++;
        }
        os << *it;
    }
    os << "}";
    return os;
}

template <typename K, typename C>
ostream& operator << (ostream& os, const multiset<K, C> V) {
    os << "{";
    if(!V.empty()){
        auto it = V.begin();
        for (int i = 0; i < V.size() -1; ++i) {
            os << *it << " ";
            it++;
        }
        os << *it;
    }
    os << "}";
    return os;
}

template <typename K, typename T, typename C>
ostream& operator << (ostream& os, const map<K,T,C> V) {
    os << "{";
    if(!V.empty()){
        auto it = V.begin();
        for (int i = 0; i < V.size() -1; ++i) {
            os << "(";
            os << it->first << "," << it->second;
            os << ") ";
            it++;
        }
        os << "(";
        os << it->first << "," << it->second;
        os << ")";
    }
    os << "}";
    return os;
}

template <typename K, typename T, typename C>
ostream& operator << (ostream& os, const unordered_map<K,T,C> V) {
    os << "{";
    if(!V.empty()){
        auto it = V.begin();
        for (int i = 0; i < V.size() -1; ++i) {
            os << "(";
            os << it->first << "," << it->second;
            os << ") ";
            it++;
        }
        os << "(";
        os << it->first << "," << it->second;
        os << ")";
    }
    os << "}";
    return os;
}

template <typename T>
ostream& operator << (ostream& os, const deque<T> V) {
    os << "[";
    if (!V.empty()) {
        for (int i = 0; i < V.size() - 1; ++i) {
            os << V[i] << "->";
        }
        if (!V.empty())os << V.back();
    }
    os << "]";
    return os;
};

template <typename T, typename Cont, typename Comp>
ostream& operator << (ostream& os, const priority_queue<T, Cont, Comp> V) {
    priority_queue<T, Cont, Comp> _V = V;
    os << "[";
    if(!_V.empty()){
        while(_V.size() > 1){
            os << _V.top() << "->";
            _V.pop();
        }
        os << _V.top();
    }
    os << "]";
    return os;
};

template <class F>
struct y_combinator {
    F f; // the lambda will be stored here

    // a forwarding operator():
    template <class... Args>
    decltype(auto) operator()(Args&&... args) const {
        // we pass ourselves to f, then the arguments.
        // the lambda should take the first argument as `auto&& recurse` or similar.
        return f(*this, std::forward<Args>(args)...);
    }
};
// helper function that deduces the type of the lambda:
template <class F>
y_combinator<std::decay_t<F>> recursive(F&& f){
return {std::forward<F>(f)};
}

struct hash_pair {
    template <class T1, class T2>
    size_t operator()(const pair<T1, T2>& p) const
    {
        auto hash1 = hash<T1>{}(p.first);
        auto hash2 = hash<T2>{}(p.second);
        return hash1 ^ hash2;
    }

};

 /*
struct X{
    int x,y,id;
    bool operator < (const X R)const{
        return id < R.id;
    }
    friend ostream& operator << (ostream& os,  X R){
        os << "(" << R.x << "," << R.y << "," << R.id << ")";
    }
    friend bool operator == (const X L,  const X R){
        return L.id == R.id;
    }
*/
 template <signed M, unsigned T>
 struct mod_int {
     constexpr static signed MODULO = M;
     constexpr static unsigned TABLE_SIZE = T;

     signed x;

     mod_int() : x(0) {}

     mod_int(long long y) : x(static_cast<signed>(y >= 0 ? y % MODULO : MODULO - (-y) % MODULO)) {}

     mod_int(int y) : x(y >= 0 ? y % MODULO : MODULO - (-y) % MODULO) {}

     mod_int &operator+=(const mod_int &rhs) {
         if ((x += rhs.x) >= MODULO) x -= MODULO;
         return *this;
     }

     mod_int &operator-=(const mod_int &rhs) {
         if ((x += MODULO - rhs.x) >= MODULO) x -= MODULO;
         return *this;
     }

     mod_int &operator*=(const mod_int &rhs) {
         x = static_cast<signed>(1LL * x * rhs.x % MODULO);
         return *this;
     }

     mod_int &operator/=(const mod_int &rhs) {
         x = static_cast<signed>((1LL * x * rhs.inv().x) % MODULO);
         return *this;
     }

     mod_int operator-() const { return mod_int(-x); }

     mod_int operator+(const mod_int &rhs) const { return mod_int(*this) += rhs; }

     mod_int operator-(const mod_int &rhs) const { return mod_int(*this) -= rhs; }

     mod_int operator*(const mod_int &rhs) const { return mod_int(*this) *= rhs; }

     mod_int operator/(const mod_int &rhs) const { return mod_int(*this) /= rhs; }

     bool operator<(const mod_int &rhs) const { return x < rhs.x; }

     mod_int inv() const {
         assert(x != 0);
         if (x <= static_cast<signed>(TABLE_SIZE)) {
             if (_inv[1].x == 0) prepare();
             return _inv[x];
         } else {
             signed a = x, b = MODULO, u = 1, v = 0, t;
             while (b) {
                 t = a / b;
                 a -= t * b;
                 std::swap(a, b);
                 u -= t * v;
                 std::swap(u, v);
             }
             return mod_int(u);
         }
     }

     mod_int pow(long long t) const {
         assert(!(x == 0 && t == 0));
         mod_int e = *this, res = mod_int(1);
         for (; t; e *= e, t >>= 1)
             if (t & 1) res *= e;
         return res;
     }

     mod_int fact() {
         if (_fact[0].x == 0) prepare();
         return _fact[x];
     }

     mod_int inv_fact() {
         if (_fact[0].x == 0) prepare();
         return _inv_fact[x];
     }

     mod_int choose(mod_int y) {
         assert(y.x <= x);
         return this->fact() * y.inv_fact() * mod_int(x - y.x).inv_fact();
     }

     static mod_int _inv[TABLE_SIZE + 1];

     static mod_int _fact[TABLE_SIZE + 1];

     static mod_int _inv_fact[TABLE_SIZE + 1];

     static void prepare() {
         _inv[1] = 1;
         for (int i = 2; i <= (int)TABLE_SIZE; ++i) {
             _inv[i] = 1LL * _inv[MODULO % i].x * (MODULO - MODULO / i) % MODULO;
         }
         _fact[0] = 1;
         for (unsigned i = 1; i <= TABLE_SIZE; ++i) {
             _fact[i] = _fact[i - 1] * int(i);
         }
         _inv_fact[TABLE_SIZE] = _fact[TABLE_SIZE].inv();
         for (int i = (int)TABLE_SIZE - 1; i >= 0; --i) {
             _inv_fact[i] = _inv_fact[i + 1] * (i + 1);
         }
     }
 };

 template <int M, unsigned F>
 std::ostream &operator<<(std::ostream &os, const mod_int<M, F> &rhs) {
     return os << rhs.x;
 }

 template <int M, unsigned F>
 std::istream &operator>>(std::istream &is, mod_int<M, F> &rhs) {
     long long s;
     is >> s;
     rhs = mod_int<M, F>(s);
     return is;
 }

 template <int M, unsigned F>
 mod_int<M, F> mod_int<M, F>::_inv[TABLE_SIZE + 1];

 template <int M, unsigned F>
 mod_int<M, F> mod_int<M, F>::_fact[TABLE_SIZE + 1];

 template <int M, unsigned F>
 mod_int<M, F> mod_int<M, F>::_inv_fact[TABLE_SIZE + 1];

 template <int M, unsigned F>
 bool operator==(const mod_int<M, F> &lhs, const mod_int<M, F> &rhs) {
     return lhs.x == rhs.x;
 }

 template <int M, unsigned F>
 bool operator!=(const mod_int<M, F> &lhs, const mod_int<M, F> &rhs) {
     return !(lhs == rhs);
 }

 const int MF = 1000010;
 const int MOD = 1000000007;

 using mint = mod_int<MOD, MF>;

 mint binom(int n, int r) { return (r < 0 || r > n || n < 0) ? 0 : mint(n).choose(r); }

 mint fact(int n) { return mint(n).fact(); }

 mint inv_fact(int n) { return mint(n).inv_fact(); }
template<class T>void Chmod(T &a, const T &m) {a = MOD(a, m);}
template<class T>bool Chmax(T &a, const T &b) { if (a<b) { a=b; return 1; } return 0; }
template<class T>bool Chmin(T &a, const T &b) { if (b<a) { a=b; return 1; } return 0; }
//256MB = 2^29(~5.3*10^8)*sizeof(int)
#define int ll //2^31=2.15*10^9, 2^63=9.22*10^18
class SDigitSum {
public:

void solve(std::istream& cin, std::ostream& cout, std::ostream& cerr) {
    string K;int D;
    cin >> K >> D;
//    VI a(SZ(K));
    int a[SZ(K)] = {};
//    VM3 (dp, SZ(K) + 5, D+1,2,0);
    int dp[SZ(K)+5][D+1][2]= {};
    dp[0][0][1] = 1;
    REP(i,SZ(K))a[i] = K[i] - '0';
    REP(n,SZ(K))REP(d,D){
            REP(i,10)dp[n+1][(d+i)%D][0] += dp[n][d][0], Chmod(dp[n+1][(d+i)%D][0], mod);
            REP(i,a[n])dp[n+1][(d+i)%D][0] += dp[n][d][1], Chmod(dp[n+1][(d+i)%D][0], mod);
            dp[n+1][(d+a[n])%D][1] = dp[n][d][1];
            ERR(n,d,dp[n][d][0], dp[n][d][1])
    }
    print(MOD(dp[SZ(K)][0][0] + dp[SZ(K)][0][1] - 1, mod));

}


};


#undef int
int main() {

	SDigitSum solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
    std::ostringstream err;
	in.tie(0); ios::sync_with_stdio(0);
//	solver.solve(in, out);
    solver.solve(in, out,err);
	return 0;
}
