/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author aps
 */

#include "bits/stdc++.h"

using namespace std;

#define int long long int
#define all(x) x.begin(), x.end()
#define pb push_back
#define mp make_pair
#define se second
#define fi first

typedef pair<int, int> pii;
typedef vector<int> vi;

const int inf = 1e18;
const int mod = 1e9+7;

inline int add(int x, int y) { x += y; if (x >= mod) x -= mod; return x;}
inline int sub(int x, int y) { x -= y; if (x < 0) x += mod; return x;}
inline int mul(int x, int y) { return ((x % mod) * (y % mod)) % mod;}
inline int power(int a, int b) {
    int x = 1;
    while (b) {
        if (b & 1) x = mul(x, a);
        a = mul(a, a);
        b >>= 1;
    }
    return x;
}
inline int inv(int a) { return power(a, mod - 2);}

int dp[100005][105][2],n,d;
string s;


class SDigitSum {
public:

    int f(int i,int small,int m){
        int& ret = dp[i][m][small];
        if(ret != -1) return ret;

        if(i == n) return ret = (m==0?1:0);

        ret = 0;
        int lim = (small ? 9 : s[i]-'0');
        for(int use=0;use<=lim;use++){
            ret=add(ret,f(i+1,(use < s[i]-'0' ? 1:small),(m+use)%d));
        }
        return ret;
    }

    void solve(std::istream& cin, std::ostream& cout){
        cin >> s >> d;
        n = s.length();

        memset(dp,-1,sizeof dp);
        cout << sub(f(0,0,0),1) << endl;
    }
};


int32_t main() {
    ios_base::sync_with_stdio(false); cin.tie(nullptr); cout.tie(nullptr);
    SDigitSum solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
