/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Apolloliu
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>

using namespace std;

void get() {

}

char s[110][110];
unordered_map<int,int>mp;
class BGridCompression {
public:
	void solve(std::istream& in, std::ostream& out) {
		int n, m;
		in >> n >> m;
		for (int i = 0; i < n; ++i) {
			in >> s[i];
		}
		int rl, rr, cl, cr;
		rl = n; cl = m; rr = cr = 0;
		for (int i = 0; i < n; ++i) {
			for (int j = 0; j < m; ++j) {
				if(s[i][j] == '#'){
					rl = min(rl, i);
					rr = max(rr, i);
					cl = min(cl, j);
					cr = max(cr, j);
				}
			}
		}
		mp.clear();
		for (int j = cl; j <= cr; ++j) {
			int sum = 0;
			for (int i = rl; i <= rr; ++i) {
				if(s[i][j] == '#')sum++;
			}
			if(!sum)mp[j] = 1;
		}
		for (int i = rl; i <= rr; ++i) {
			int sum = 0;
			for (int j = cl; j <= cr; ++j) {
				if(s[i][j] == '#')sum ++;
			}
			if(!sum)continue;
			for (int j = cl; j <= cr; ++j) {
				if(mp[j] == 1)continue;
			    out << s[i][j];
			}
			out << '\n';
		}
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	BGridCompression solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}