#include <bits/stdc++.h>
using namespace std;



// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
  long long H,W;

  cin >> H >> W;

  vector<string> as(H);
  vector<bool> vartical(W, true);
  vector<bool> horizontal(H, true);

  for(long long i = 0; i < H; i++){
    cin >> as.at(i);

    bool isall = true;

    for(long long j = 0; j < W; j++){
      if(as[i][j] == '#'){
        isall = false;
        vartical[j] = false;
      }
    }

    if(!isall) horizontal[i] = false;
  }

  for(long long i = 0; i < H; i++) {
    if(horizontal[i]) continue;
    for(long long j = 0; j < W; j++) {
      if(!vartical[j]) cout << as[i][j];
    }
    cout << endl;
  }

  return 0;
}
