/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <algorithm>
#include <fstream>
#include <functional>
#include <iostream>
#include <iomanip>
#include <iterator>
#include <queue>
#include <set>
#include <stack>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

#define ll long long int
#define REP(i, n) for(int i=0;i<n;++i)
#define ALL(a) (a).begin(),(a).end()

using namespace std;


class BGridCompression {
public:
    ll H, W;
    char mat[100][100];
    bool hskip[100]{false};
    bool wskip[100]{false};

    void solve(std::istream& in, std::ostream& out) {
        in >> H >> W; in.ignore();
        string line;
        REP(i, H) {
            getline(in, line);
            REP(j, W) mat[i][j] = line[j];
        }

        for(;;) {
            REP(i, H) {
                if (row(i) && !hskip[i]) { hskip[i] = true; continue; }
            }
            REP(j, W) {
                if (col(j) && !wskip[j]) { wskip[j] = true; continue; }
            }
            break;
        }
        REP(i, H) {
            if (hskip[i]) continue;
            REP(j, W) {
                if (!wskip[j]) out << mat[i][j];
            }
            out << endl;
        }

    }

    bool row(int r) {
        char x;
        REP(i, W) {
            if (wskip[i]) continue;
            x = mat[r][i]; break;
        }
        if (x == '#') return false;
        REP(i, W) {
            if (wskip[i]) continue;
            if (x != mat[r][i]) return false;
        }
        return true;
    }

    bool col(int c) {
        char x;
        REP(i, H) {
            if (hskip[i]) continue;
            x = mat[i][c]; break;
        }
        if (x == '#') return false;
        REP(i, H) {
            if (hskip[i]) continue;
            if (x != mat[i][c]) return false;
        }
        return true;
    }
};


int main() {
    BGridCompression solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
