/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BGridCompression {
public:
    void solve(std::istream &in, std::ostream &out) {
      int h, w;
      in >> h >> w;
      vector<string> hs(w), ws(h);
      REP(i, h) {
        string t;
        in >> t;
        REP(j, w) {
          hs[j] += t[j];
          ws[i] += t[j];
        }
      }
      vector<bool> not_show_h_index(w, false), not_show_w_index(h, false);
      REP(i, w) {
        bool f = true;
        char c = '.';
        REP(j, h) {
          f &= hs[i][j] == c;
        }
        if (f) not_show_h_index[i] = true;
      }
      REP(i, h) {
        bool f = true;
        char c = '.';
        REP(j, w) {
          f &= ws[i][j] == c;
        }
        if (f) not_show_w_index[i] = true;
      }

      REP(i, h) {
        if (!not_show_w_index[i]) {
          REP(j, w) {
            if (!not_show_h_index[j])
              out << ws[i][j];
          }
          out << endl;
        }
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BGridCompression solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
