#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG


// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    // Failed to predict input format
    int H, W;
    cin >> H >> W;

    vec2<char> field(H, vec<char>(W, 0));

    for(int i=0; i < H; i++){
        for(int j=0; j < W; j++){
            while(true){
                char temp;
                cin >> temp;
                if(temp == '#'){
                    field[i][j] = '#';
                }else if(temp == '.'){
                    field[i][j] = '.';
                }else{
                    assert(0);
                }
                break;
            }
        }
    }

    // solve
    vec2<char> rowRed;
    for(int i=0; i < H; i++){
        if(count(field.at(i).begin(), field.at(i).end(), '.') != W){
            rowRed.push_back(field.at(i));
        }
    }

    set<int> cols;
    for(int j=0; j < W; j++){
        ll cnt = 0;
        for(int i=0; i < rowRed.size(); i++){
            if(rowRed.at(i).at(j) == '.'){
                cnt++;
            }
        }
        if(cnt == rowRed.size()){
            cols.insert(j);
        }
    }


    vec2<char> res;
    for(int i=0; i < rowRed.size(); i++){
        res.push_back(vec<char>());
        for(int j=0; j < W; j++){
            if(cols.find(j) != cols.end()){
                continue;
            }
            res.back().push_back(rowRed.at(i).at(j));
        }
    }

    for(int i=0; i < res.size(); i++){
        for(int j=0; j < res[0].size(); j++){
            cout << res[i][j];
        }
        cout << endl;
    }


    return 0;
}
