/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author alireza_kaviani
 */

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<double, double> pdd;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 3e3 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 998244353; // 998244353; // 1e9 + 9;

ll n , s , ans , A[MAXN] , dp[MAXN][MAXN];

int main() {
    ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);

    cin >> n >> s;
    for(ll i = 1 ; i <= n ; i++)    cin >> A[i];

    for(ll i = 1 ; i <= n ; i++){
        for(ll j = 0 ; j < MAXN ; j++)  dp[i][j] = dp[i - 1][j];
        dp[i][A[i]] = (dp[i][A[i]] + i) % MOD;
        for(ll j = A[i] ; j < MAXN ; j++)   dp[i][j] = (dp[i][j] + dp[i - 1][j - A[i]]) % MOD;
        //cout << i << sep << dp[i][s] << endl;
        ans += ((dp[i][s] - dp[i - 1][s] + MOD) * (n - i + 1)) % MOD;
    }
    cout << ans % MOD << endl;

    return 0;
}
/*

*/
