#include <bits/stdc++.h>
using namespace std;
using ll = long long;

const long long MOD = 998244353;

ll dp[3001][3001];

void solve(long long N, long long S, std::vector<long long> A){
    
    // memset(dp,0,sizeof(dp));
    dp[0][0] = 1;
    ll ans =0;
    for(int i=0;i<N;i++){
        for(int j=0;j<=S;j++){
            if(j<A[i]){
                dp[i+1][j] = dp[i][j];
            }else{
                dp[i+1][j] = (dp[i][j-A[i]] + dp[i][j])%MOD;
            }
            if(j==0){
                dp[i+1][j]++;
            }
           
        }
        
        // cerr << "i+1=" <<i+1 <<"num =" <<dp[i+1][S] << endl;
        ans = (ans + dp[i+1][S])%MOD;
    }
    cout <<ans << endl;

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long S;
    scanf("%lld",&S);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, S, std::move(A));
    return 0;
}
