/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;

class TaskB {
 public:
  void solve(std::istream &in, std::ostream &out) {
    int X, Y, Z;
    in >> X >> Y >> Z;
    out << (X - Z) / (Y + Z);
  }
};


int main() {
  TaskB solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
