/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author aajisaka
 */

#include<bits/stdc++.h>

using namespace std;

void debug_out() { cerr << endl; }
template <typename Head, typename... Tail>
void debug_out(Head H, Tail... T) {
  cerr << " " << to_string(H);
  debug_out(T...);
}
#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

#define SPEED ios_base::sync_with_stdio(false);cin.tie(nullptr)
#define rep(i,n) for(int i=0; i<(int)(n); i++)
#define all(v) v.begin(), v.end()
template<class T> inline bool chmax(T& a, T b) { if (a < b) { a = b; return true; } return false; }
template<class T> inline bool chmin(T& a, T b) { if (a > b) { a = b; return true; } return false; }

using ll = long long;
using P = pair<ll, ll>;

constexpr double PI = 3.14159265358979323846;
mt19937_64 engine(chrono::steady_clock::now().time_since_epoch().count());

class DBlackAndWhiteTree {
public:

    vector<int> graph[100005];
    vector<int> sort;
    vector<bool> used;

    void dfs(int p) {
      used[p] = true;
      for(auto e: graph[p]) {
        if (used[e]) continue;
        dfs(e);
      }
      sort.push_back(p);
    }

    void solve(istream& cin, ostream& cout) {
      SPEED;
      int n; cin >> n;
      used.resize(n);
      if (n%2 == 1) {
        cout << "First" << endl;
        return;
      }

      rep(i, n-1) {
        int a, b; cin >> a >> b;
        a--; b--;
        graph[a].push_back(b);
        graph[b].push_back(a);
      }
      dfs(0);
      rep(i, n) used[i] = false;

      for(auto p: sort) {
        if (used[p]) continue;
        bool flag = false;
        for(auto e: graph[p]) {
          if (used[e]) continue;
          used[e] = true;
          flag = true;
          break;
        }
        if (!flag) {
          cout << "First" << endl;
          return;
        }
      }
      cout << "Second" << endl;
    }
};

signed main() {
  DBlackAndWhiteTree solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}