/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author HARSHAD
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long int ll;

class TaskC {
public:
	void solve(std::istream& in, std::ostream& out) {
		int n; in>>n;
		vector<pair<int, int>> arr;
		for(int i = 0; i<n; ++i){
		    int x; in>>x;
			arr.emplace_back(x, i);
		}
		sort(arr.begin(), arr.end());
		vector<int> res(n);
		int a = arr[n/2].first, b = arr[n/2-1].first;
		for(int i = 0; i<n; ++i){
			if(i<n/2) res[arr[i].second] = a;
			else res[arr[i].second] = b;
		}
		for(int x: res) out<<x<<"\n";
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	TaskC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
