/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: alireza_kaviani
 * Time: 2020-05-18 22:40:16
**/
#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;

typedef long long ll;
typedef long double ld;
typedef pair<ll, ll> pll;

#define all(x)                      (x).begin(),(x).end()
#define Sort(x)                     sort(all((x)))
#define X                           first
#define Y                           second
#define sep                         ' '
#define endl                        '\n'
#define SZ(x)                       ll(x.size())

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 1e3 + 10;
const ll LOG = 22;
const ll INF = 8e18;
const ll MOD = 1e9 + 7; // 998244353; // 1e9 + 9;

ll n , A , B , C , D , fact[MAXN] , inv[MAXN][MAXN] , dp[MAXN][MAXN];

int main() {
    ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);

    for(int i = 0 ; i < MAXN ; i++){
        fact[i] = (i == 0 ? 1LL : fact[i - 1] * i) % MOD;
        inv[i][0] = 1;
        inv[i][1] = poww(fact[i] , MOD - 2 , MOD);
        for(int j = 2 ; j < MAXN ; j++) inv[i][j] = inv[i][j - 1] * inv[i][1] % MOD;
    }

    cin >> n >> A >> B >> C >> D;
    dp[A - 1][0] = 1;
    for(int i = A ; i <= B ; i++){
        for(int j = 0 ; j < MAXN ; j++) dp[i][j] = dp[i - 1][j];
        for(int j = C ; j <= D ; j++){
            if(i * j > n)   break;
            ll cur = fact[i * j] * inv[i][j] % MOD * inv[j][1] % MOD;
            //cout << i << sep << j << sep << cur << endl;
            for(int k = i * j ; k <= n ; k++){
                ll x = fact[n - k + i * j] * inv[i * j][1] % MOD * inv[n - k][1] % MOD;
                dp[i][k] = (dp[i][k] + dp[i - 1][k - i * j] * x % MOD * cur) % MOD;
            }
        }
    }
    cout << dp[B][n] << endl;


    return 0;
}
/*

*/
