#line 1 "main.cpp"
#include <bits/stdc++.h>
#line 2 "/home/user/GitHub/competitive-programming-library/utils/macros.hpp"
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) std::begin(x), std::end(x)
#line 4 "/home/user/GitHub/competitive-programming-library/utils/binary_search.hpp"

/**
 * @brief a binary search / 二分探索
 * @param[in] p  a monotone predicate defined on $[l, r)$
 * @return $\min \lbrace x \in [l, r) \mid p(x) \rbrace$, or r if it doesn't exist
 */
template <typename UnaryPredicate>
int64_t binsearch(int64_t l, int64_t r, UnaryPredicate p) {
    assert (l <= r);
    -- l;
    while (r - l > 1) {
        int64_t m = l + (r - l) / 2;
        (p(m) ? r : l) = m;
    }
    return r;
}

/**
 * @return $\max \lbrace x \in (l, r] \mid p(x) \rbrace$, or l if it doesn't exist
 */
template <typename UnaryPredicate>
int64_t binsearch_max(int64_t l, int64_t r, UnaryPredicate p) {
    assert (l <= r);
    ++ r;
    while (r - l > 1) {
        int64_t m = l + (r - l) / 2;
        (p(m) ? l : r) = m;
    }
    return l;
}
#line 4 "main.cpp"
using namespace std;
template <class T, class U> inline void chmax(T & a, U const & b) { a = max<T>(a, b); }
template <class T, class U> inline void chmin(T & a, U const & b) { a = min<T>(a, b); }

int64_t solve(int n, const vector<int64_t> & a) {
    constexpr int64_t INF = 1e18;
    if (n % 2 == 0) {
        vector<array<int64_t, 2> > dp(n + 1, { -INF, -INF });
        dp[0][0] = 0;
        dp[1][0] = a[0];
        dp[2][1] = a[1];
        REP3 (i, 2, n) {
            chmax(dp[i + 1][0], dp[i - 1][0] + a[i]);
            chmax(dp[i + 1][1], dp[i - 1][1] + a[i]);
            chmax(dp[i + 1][1], dp[i - 2][0] + a[i]);
        }
        return max(dp[n - 1][0], dp[n][1]);
    } else {
        vector<array<int64_t, 3> > dp(n + 1, { -INF, -INF, -INF });
        dp[0][0] = 0;
        dp[1][0] = a[0];
        dp[2][1] = a[1];
        dp[3][0] = a[0] + a[2];
        dp[3][2] = a[2];
        REP3 (i, 3, n) {
            chmax(dp[i + 1][0], dp[i - 1][0] + a[i]);
            chmax(dp[i + 1][1], dp[i - 2][0] + a[i]);
            chmax(dp[i + 1][1], dp[i - 1][1] + a[i]);
            chmax(dp[i + 1][2], dp[i - 3][0] + a[i]);
            chmax(dp[i + 1][2], dp[i - 2][1] + a[i]);
            chmax(dp[i + 1][2], dp[i - 1][2] + a[i]);
        }
        return max({ dp[n - 2][0], dp[n - 1][1], dp[n][2] });
    }
}

// generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    constexpr char endl = '\n';
    int N;
    cin >> N;
    vector<int64_t> A(N);
    REP (i, N) {
        cin >> A[i];
    }
    auto ans = solve(N, A);
    cout << ans << endl;
    return 0;
}
