/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author aajisaka
 */

#include<bits/stdc++.h>

using namespace std;

void debug_out() { cerr << endl; }
template <typename Head, typename... Tail>
void debug_out(Head H, Tail... T) {
  cerr << " " << to_string(H);
  debug_out(T...);
}
#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

#define SPEED ios_base::sync_with_stdio(false);cin.tie(nullptr)
#define rep(i,n) for(int i=0; i<(int)(n); i++)
#define all(v) v.begin(), v.end()
template<class T> inline bool chmax(T& a, T b) { if (a < b) { a = b; return true; } return false; }
template<class T> inline bool chmin(T& a, T b) { if (a > b) { a = b; return true; } return false; }

using ll = long long;
using P = pair<ll, ll>;

constexpr long double PI = 3.14159265358979323846264338327950288L;
mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());

class FSelectHalf {
public:
    void solve(istream& cin, ostream& cout) {
      SPEED;
      int n; cin >> n;
      vector<ll> a(n);
      rep(i, n) {
        cin >> a[i];
      }
      ll dp[n+1][5][4];
      rep(i, n+1) rep(j, 5) rep(k, 4) {
        dp[i][j][k] = LLONG_MIN/2;
      }
      dp[0][2][1] = 0;
      for(int i=0; i<n; i++) {
        if (i%2==0) {
          // not take
          for(int j=0; j<5; j++) {
            for(int k=0; k<3; k++) {
              chmax(dp[i+1][j][k+1], dp[i][j][k]);
            }
          }
          // take
          for(int j=0; j<4; j++) {
            for(int k=1; k<4; k++) {
              chmax(dp[i+1][j+1][0], dp[i][j][k] + a[i]);
            }
          }
        } else {
          // not take
          for(int j=1; j<5; j++) {
            for(int k=0; k<3; k++) {
              chmax(dp[i+1][j-1][k+1], dp[i][j][k]);
            }
          }
          // take
          for(int j=0; j<5; j++) {
            for(int k=1; k<4; k++) {
              chmax(dp[i+1][j][0], dp[i][j][k] + a[i]);
            }
          }
        }
      }

      ll ans = LLONG_MIN;
      rep(k, 4) {
        chmax(ans, dp[n][2][k]);
      }

      cout << ans << endl;

    }
};

signed main() {
  FSelectHalf solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}