// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools

#include <bits/stdc++.h>

using namespace std;

using i64 = long long;

const i64 MOD = 1e9 + 7;
const i64 INF = i64(1e18) + 7;


template <typename T>
bool chmin(T& x, T y){
    if(x > y){
        x = y;
        return true;
    }
    return false;
}

template <typename T>
bool chmax(T& x, T y){
    if(x < y){
        x = y;
        return true;
    }
    return false;
}


void solve(long long n, std::vector<long long> a){

    i64 ans = -INF;
    vector<vector<i64>> dp(n, vector<i64>(10, -INF));
    dp[0][0] = a[0];
    dp[1][0] = a[1];
    for(int i = 0; i < n; ++i){
        for(int j = 0; j < 10; ++j){
            int perf = (i / 2) + 1;
            int cnt = perf - j;
            if(cnt == 0)
                chmax(dp[i][j], 0LL);
            if(cnt == 1)
                chmax(dp[i][j], a[i]);
            if(cnt == n / 2)
                chmax(ans, dp[i][j]);
            for(int nex = 2; nex < 10 && i + nex < n; ++nex){
                int nex_idx = i + nex;
                int nex_perf = (i + nex) / 2 + 1;
                int diff = nex_perf - (cnt + 1);
                if(diff >= 10)
                    continue;
                chmax(dp[nex_idx][diff], dp[i][j] + a[nex_idx]);
            }
        }
    }
    cout << ans << endl;
}


signed main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
