#include <bits/stdc++.h>
using namespace std;
using ll = long long;


void solve(long long N, std::vector<long long> A){
    ll dp[N] = {};
    dp[0] = A[0];
    dp[1] = A[1];
    if(N%2 ==0){
        
        for(int i=1;i<N/2;i++){
            dp[i*2] = dp[i*2-2] + A[i*2];
            dp[i*2+1] = max(dp[i*2-1] + A[i*2+1],dp[i*2-2]+A[i*2+1]);
        }
        cout << max(dp[N-1],dp[N-2]) << endl;
        return;
    }else{
        dp[2] = A[2];
        for(int i=1;i <N/2;i++){
            ll temp =  max(dp[i*2-1],dp[i*2-2]);
            dp[i*2 +2] = max(temp,dp[i*2])+ A[i*2+2];
            dp[i*2 +1] = temp + A[i*2 +1];
            dp[i*2] = dp[i*2-2] + A[i*2];
        }
        ll ans = max(dp[N-1],dp[N-2]);
        cout << max(ans,dp[N-3]) << endl;
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
