/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

//<editor-fold desc="definitions">
#include <bits/stdc++.h>
#define se cout << "test ok" << endl;
#define sp << " " <<
#define enl "\n"
using namespace std;
using ll=long long;
using ld=long double;
using pi = pair<int, int>;
using pl = pair<ll, ll>;
using vi = vector<int>;
using vii = vector<vector<int>>;
using viii = vector<vector<vector<int>>>;
using vl = vector<ll>;
using vll = vector<vector<ll>>;
using vlll = vector<vector<vector<ll>>>;
template<class T> using V = vector<T>;
template<class T> using VV = vector<vector<T>>;
template<class T> using VVV = vector<vector<vector<T>>>;
template<class T1, class T2> using P = pair<T1, T2>;
ll mod = ll(1e9)+7;
ll inf = ll(1e18);
void bl(bool b, ostream& out=cout){ out << (b ? "Yes" : "No") << endl; }
void bl2(bool b, ostream& out=cout){ out << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b){a=b; return true;} return false; }
template<typename T> inline bool chmin(T &a, T b){ if(a>b){a=b; return true;} return false; }
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};

#ifndef INCLUDE_DEBUG_HPP
#define INCLUDE_DEBUG_HPP

#define TO_STRING(varName) # varName
#include <iostream>
#include <vector>
#include <map>
#include <set>
using namespace std;

namespace dbg {

using ll = long long;

class Debug {
  void prefix() { cout << "\033[7m\033[35m" << " DEBUG " << "\033[0m" << endl; }

  void out_helper(){ cout << endl; }

  void out_with_name_helper(){ cout << endl; }

  template<typename T1, typename... T2>
  void out_helper(T1 v, T2... args);

  template<typename T1, typename... T2>
  void out_with_name_helper(string s, T1 v, T2... args);

  // value
  template<typename T>
  void print(T val);

  // pair
  template<typename A, typename B>
  void print(pair<A, B> p);

  // tuple
  template<typename A, typename B, typename C>
  void print(tuple<A, B, C> t);

  // vector
  template<typename T>
  void print(vector<T> &vec);

  // set
  template<typename T>
  void print(set<T> &st);

  // map
  template<typename A, typename B>
  void print(map<A, B> mp);
public:
  Debug(){}

  template<typename... T>
  void out(T... args){
    prefix();
    out_helper(args...);
  }

  template<typename... T>
  void out_with_name(T... args){
    prefix();
    out_with_name_helper(args...);
  }

  template<typename T>
  void outg(vector<vector<T>> &g) {
    prefix();
    for(auto& v1 : g){
      for(auto& v2 : v1) {
        cout << v2 << " ";
      }
      cout << endl;
    }
  }
};

template<typename T1, typename... T2>
void Debug::out_helper(T1 v, T2... args) {
  print(v); cout << endl;
  out_helper(args...);
}

template<typename T1, typename... T2>
void Debug::out_with_name_helper(string s, T1 v, T2... args) {
  cout << s << ": "; print(v); cout << endl;
  out_with_name_helper(args...);
}

template<typename T>
void Debug::print(T val){
  cout << val;
}

template<typename A, typename B>
void Debug::print(pair<A, B> p){
  cout << "("; print(p.first); cout << ", "; print(p.second); cout << ")";
}

template<typename A, typename B, typename C>
void Debug::print(tuple<A, B, C> t) {
  cout << "("; print(get<0>(t)); cout << ", "; print(get<1>(t)); cout << ", "; print(get<2>(t)); cout << ")";
}

template<typename T>
void Debug::print(vector<T>& vec) {
  cout << "[";
  bool fir = true;
  for(auto& e : vec) {
    if(!fir) cout << " ";
    print(e), fir=false;
  }
  cout << "]";
}

template<typename T>
void Debug::print(set<T> &st){
  cout << "{";
  bool fir = true;
  for(auto& e : st) {
    if(!fir) cout << " ";
    print(e), fir=false;
  }
  cout << "}";
}

template<typename A, typename B>
void Debug::print(map<A, B> mp){
  cout << "{";
  bool fir = true;
  for(auto& p : mp){
    if(!fir) cout << " ";
    print(p), fir=false;
  }
  cout << "}";
}

}

#endif //INCLUDE_DEBUG_HPP

dbg::Debug debug;
//</editor-fold>

class FSelectHalf {
public:
  void solve(std::istream& in, std::ostream& out){
    int n;
    in >> n;
    vl a(n);
    ll even=0, odd=0;
    for(int i=0; i<n; i++) {
      in >> a[i];
      if(i&1) odd += a[i];
      else even += a[i];
    }

    vll dp(n+1, vl(3, -inf));
    dp[0][0] = 0;
    for(int i=0; i<n; i++){
      for(int j=0; j<3; j++){
        if(j+1 < 3){
          chmax(dp[i+1][j+1], dp[i][j]);
        }
        chmax(dp[i+1][j], dp[i][j] + ((i+j)%2 ? 0LL : a[i]));
      }
    }

    if(n&1)
      out << dp[n][2] << endl;
    else
      out << dp[n][1] << endl;
  }
};


int main() {
  cin.tie(nullptr);
  ios_base::sync_with_stdio(false);
  FSelectHalf solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}
