/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Miguel Mini
 */

#include <bits/stdc++.h>
#define sz(x) (int)x.size()
#define trav(v, x) for (auto v : x)
#define re(x, y, z) for (int x=y; x<z; ++x)
#define all(x) x.begin(), x.end()
#define rall(x) x.rbegin(), x.rend()
using namespace std;
using ll = long long;
using ii = pair<int, int>;
using vi = vector<int>;
const int maxn = 2e5 + 10;
long long memo[2][maxn];
long long memo2[2][maxn];
int a[maxn];

class F {
public:
    long long get(int a[], int n) {
        memo[0][0] = a[0];
        memo[1][0] = a[1];
        for (int i = 2; i < n; i += 2) {
            memo[0][i] = memo[0][i-2] + a[i];
            memo[1][i] = max(memo[0][i-2], memo[1][i-2]) + a[i+1];
        }
        return  max(memo[0][n-2], memo[1][n-2]);
    }
    int testNumber = 0;
	void solve(istream& in, ostream& out) {
        //out << "Case #" << ++testNumber << ": ";
        int n;
        in >> n;
        re(i, 0, n) in >> a[i];
        long long ans;
        if (n & 1) {
            memo[0][0] = a[0];
            memo[1][0] = a[1];
            for (int i = 2; i < n; i += 2) {
                memo[0][i] = memo[0][i-2] + a[i];
                memo[1][i] = max(memo[0][i-2], memo[1][i-2]) + a[i+1];
            }
            reverse(a, a+n);
            memo2[0][0] = a[0];
            memo2[1][0] = a[1];
            for (int i = 2; i < n; i += 2) {
                memo2[0][i] = memo2[0][i-2] + a[i];
                memo2[1][i] = max(memo2[0][i-2], memo2[1][i-2]) + a[i+1];
            }
            reverse(a, a+n);
            ans = -1e18;
            for (int i = 0; i < n; ++i) {
                if (i&1) {
                    ll temp11 = i<3?0:memo[0][i-3];
                    ll temp12 = i<3?0:memo[1][i-3];
                    ll temp21 = i+4>n?0:memo2[1][n-i-4];
                    ll temp22 = i+4>n?0:memo2[0][n-i-4];

                    //[0 1 2] 3 4 5 6
                    //1 -> 2
                    //n-1-(i+3)


                    ans = max(ans, temp11 + a[i-1] + max(temp21, temp22));
                    ans = max(ans, max(temp11, temp12) + a[i+1] + temp22);
                } else {
                    ll temp = i<2?0:max(memo[0][i-2], memo[1][i-2]);
                    ll temp2 = i+3>n?0:max(memo2[1][n-i-3], memo2[0][n-i-3]);
                    ans = max(ans, temp + temp2);
                }
                //if (ans == 298) {
                //    cout << i << endl;
                 //   break;
                //}
            }
            //a[n] = 0;
            //ans = max(ans, get(a, n+1));
            //reverse(a, a+n);
            //ans = max(ans, get(a, n+1));
        } else ans = get(a, n);
        out << ans << endl;
	}
};

int main() {
	F solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}