/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (win, osx, linux)
 * Author: step_by_step
 * Time: 2020-03-19 17:35:03
**/

//#pragma comment(linker, "/stack:200000000")
//#pragma GCC optimize("Ofast")
//#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")
//#pragma GCC optimize("unroll-loops")
  
#include <iostream>
#include <stdlib.h>
#include <cmath>
#include <algorithm>
#include <vector>
#include <queue>
#include <deque>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <random>
#include <assert.h>
#include <memory.h>
#include <time.h>
#include <bitset>

#define uint unsigned int
#define ll long long
#define ull unsigned long long
#define ld long double
#define rep(i, l, r) for (int i = (l); i < (r); i++)
#define repb(i, r, l) for (int i = (r); i > (l); i--)
#define sz(a) (int)a.size()
#define fi first
#define se second
#define mp(a, b) make_pair(a, b)
#define rank qwertyuio
#define next dfghjk
#define prev fhsgfhjf
#define plus fsghsf
#define minus ytryr
  
using namespace std;
  
inline bool setmin(int &x, int y) { return (y < x) ? x = y, 1 : 0; }
inline bool setmax(int &x, int y) { return (y > x) ? x = y, 1 : 0; }
inline bool setmin(ll &x, ll y) { return (y < x) ? x = y, 1 : 0; }
inline bool setmax(ll &x, ll y) { return (y > x) ? x = y, 1 : 0; }
  
const int N = 300000 + 1;
const int inf = (int)1e9 + 1;
const ll big = (ll)1e18 + 1;
const int P = 239;
const int P1 = 31;
const int P2 = 57;
const int MOD = (int)1e9 + 7;
const int MOD1 = (int)1e9 + 9;
const int MOD2 = 998244353;
const ld eps = 1e-9;
const double pi = atan2(0, -1);
const int ABC = 26;

int main()
{
    //freopen("circus.in", "r", stdin);
    //freopen("circus.out", "w", stdout);
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.precision(20);
    cout << fixed;
    //ll TL = 10.95 * CLOCKS_PER_SEC;
    //clock_t time = clock();
    int n;
    cin >> n;
    int a[n];
    rep(i, 0, n) {
        cin >> a[i];
    }
    ll dp[n][2][2];
    rep(i, 0, n) {
        rep(j, 0, 2) {
            rep(k, 0, 2) {
                dp[i][j][k] = -big;
            }
        }
    }
    dp[0][1][0] = a[0];
    dp[0][0][1] = 0;
    rep(i, 0, n - 1) {
        rep(j, 0, 2) {
            rep(k, 0, 2) {
                // not take i+1
                int have = (i + 2) / 2 - k;
                if ((i + 3) / 2 - have < 2) {
                    setmax(dp[i + 1][0][(i + 3) / 2 - have], dp[i][j][k]);
                }
                // take i+1
                if (j == 0) {
                    setmax(dp[i + 1][1][(i + 3) / 2 - (have + 1)], dp[i][j][k] + a[i + 1]);
                }
            }
        }
    }
    ll ans = -big;
    rep(j, 0, 2) {
        rep(k, 0, 2) {
            if ((n - 1 + 2) / 2 - k == n / 2) {
                setmax(ans, dp[n - 1][j][k]);
            }
        }
    }
    cout << ans << "\n";
    return 0;
}

