#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, std::vector<long long> s)
{
    // A - B = CとおいてCについて考える
    // 経由する番号は順に
    // 0, A, C, A+C, 2C, A+2C, …, kC, A+kC(=N-1)
    ll ans = 0;
    for (ll c = 1; c <= N; c++) {
        ll score = 0;

        for (ll k = 0; k * c < N - 1; k++) {
            auto l = k * c; // 0, C, 2C, …, kCの列
            auto r = N - 1 - k * c; // A, A+C, A+2C, …, A+kCの列
            if (((N - 1) % c == 0) && l >= r) {
                // N-1 が C(=A-B) で割り切れる場合、かならず中央でぶつかる
                break;
            }
            if (r <= c) {
                // そうでない場合、rは最初のAまでは行ける(？)
                break;
            }
            score += s[l] + s[r];
            ans = max(ans, score);
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
#pragma GCC diagnostic ignored "-Wunused-result"
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);
    long long N;
    scanf("%lld",&N);
    std::vector<long long> s(N-1-0+1);
    for(int i = 0 ; i < N-1-0+1 ; i++){
        scanf("%lld",&s[i]);
    }
    solve(N, std::move(s));
    return 0;
}
