/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author gainullin.ildar
 */

#include <bits/stdc++.h>


#include <cmath>
#include <iostream>
#include <vector>
#include <algorithm>
#include <string>
#include <set>
#include <map>
#include <list>
#include <time.h>
#include <math.h>
#include <random>
#include <deque>
#include <queue>
#include <cassert>
#include <unordered_map>
#include <iomanip>

using namespace std;


typedef long long ll;

const int N = 1e5 + 7;

int pr[N];

int get(int v)
{
    return (v == pr[v] ? v : pr[v] = get(pr[v]));
}

bool uni(int u, int v)
{
    u = get(u), v = get(v);
    if (u == v)
    {
        return false;
    }
    pr[u] = v;
    return true;
}

class Main
{
public:
    void solve(std::istream &in, std::ostream &out)
    {
        int n;
        in >> n;
        vector<pair<pair<int, int>, int> > a;
        vector<pair<int, pair<int, int> > > w;
        for (int i = 0; i < n; i++)
        {
            pr[i] = i;
            int x, y;
            in >> x >> y;
            a.push_back({{x, y}, i});
        }
        sort(a.begin(), a.end());
        for (int i = 1; i < n; i++)
        {
            w.push_back({a[i].first.first - a[i - 1].first.first, {a[i].second, a[i - 1].second}});
        }
        for (auto &c : a)
        {
            swap(c.first.first, c.first.second);
        }
        sort(a.begin(), a.end());
        for (int i = 1; i < n; i++)
        {
            w.push_back({a[i].first.first - a[i - 1].first.first, {a[i].second, a[i - 1].second}});
        }
        sort(w.begin(), w.end());
        ll ans = 0;
        for (auto c : w)
        {
            int i = c.second.first, j = c.second.second;
            if (uni(i, j))
            {
                ans += c.first;
            }
        }
        out << ans << '\n';
    }
};


int main()
{
    ios::sync_with_stdio(0);
    Main solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
