#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S, long long K)
{
    char c = S[K - 1];

    for (int i = 0; i < N; i++)
    {
        if (S[i] == c)
        {
            cout << S[i];
        }
        else
        {
            cout << "*";
        }
    }
    cout << endl;
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::string S;
    std::cin >> S;
    long long K;
    scanf("%lld", &K);
    solve(N, S, K);
    return 0;
}
