/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author ExplodingFreeze
 */

#include <iostream>
#include <fstream>

#pragma comment(linker, "/stack:200000000")
#include <bits/stdc++.h>
#define int long long
#define f(i,a,b) for(int i=(a);i<(b);i++)
#define MOD 1000000007
using pii=std::pair<int,int>;
//mt19937 rng(chrono::steady_clock::now().time_since_epoch().count()); <-- PUT IN main()/solve()!

using namespace std;

int n,a[3005],ans[3005][3005];
class LDeque {
public:
	void solve(std::istream& in, std::ostream& out) {
		in >> n;
		f(i,0,n)
			in >> a[i];
		f(i,0,n)
			f(j,0,n)
				ans[i][j]=-1;
		out << dp(0,n-1) << "\n";
	}
	int dp(int i,int j)
	{
		if(i>j)
			return 0;
		else if(ans[i][j]==-1)
			ans[i][j]=max(a[i]-dp(i+1,j),a[j]-dp(i,j-1));
		return ans[i][j];
	}
};


int32_t main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	LDeque solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
