#include <bits/stdc++.h>
using namespace std;
using ll = long long;
const int maxN = 3000;
ll dp[maxN][maxN];
ll a[maxN];


ll dfs(int i,int j){
    if(i >j){
        return 0;
    }
    if(i==j){
        dp[i][j] = a[i];
        return dp[i][j];
    }
    ll s,t;
    if(dp[i][j-1] == -1){
        s = a[j] -dfs(i,j-1);
    }else{
        s = a[j]-dp[i][j-1];
    }
    if(dp[i+1][j] == -1){
        t = a[i]-dfs(i+1,j);
    }else{
        t = a[i]-dp[i+1][j];
    }
    dp[i][j] = max(s,t);
    // cerr << "i=" <<i<<"j="<<j <<"val=" << dp[i][j] << endl;
    return dp[i][j];
}




// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
    }
    for(int i=0;i<N;i++){
        for(int j=0;j<N;j++){
            dp[i][j] = -1;
        }
    }
    cout << dfs(0,N-1) << endl;
    return 0;
}
