/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author rahdirigs
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

const int mxN = 3010;
int a[mxN];
ll dp[mxN][mxN][2];
bool vis[mxN][mxN][2];

class TaskL {
public:
	int N;

	void solve(std::istream& in, std::ostream& out) {
		in >> N;
		for (int i = 0; i < N; i++) in >> a[i];
		memset(vis, false, sizeof(vis));
		ll ans = rec(0, N - 1, 0);
		out << ans;
	}

	ll rec(int l, int r, int t) {
		if (l > r) return 0;
		if (vis[l][r][t]) return dp[l][r][t];
		vis[l][r][t] = true;
		if (t == 0) {
			return dp[l][r][t] = max(a[l] + rec(l + 1, r, 1), a[r] + rec(l, r - 1, 1));
		} else {
			return dp[l][r][t] = min(-a[l] + rec(l + 1, r , 0), -a[r] + rec(l, r - 1, 0));
		}
	}
};

int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	TaskL solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
