/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

#define REP(i,x,y) for(int i=(x);i<(y);i++)
#define RREP(i,x,y) for(int i=(y)-1;i>=(x);i--)
#define all(x) (x).begin(),(x).end()
//#define int long long

using namespace std;

// conversion
inline int toInt(string s) {int v; istringstream sin(s);sin>>v;return v;}
template<class T> inline string toString(T x) {ostringstream sout;sout<<x;return sout.str();}

#ifdef LOCAL
#define eprintf(...) fprintf(stderr, __VA_ARGS__)
#define dump(x)  cerr << #x << " = " << (x) << endl
#define debug(x) cerr << #x << " = " << (x) << " (L" << __LINE__ << ")" << " " << __FILE__ << endl
#else
#define eprintf(...)
#define dump(x)
#define debug(x)
#endif

typedef long long ll;

const ll MOD = 1e9 + 7;

class ESequenceDecomposing {
public:
void solve(std::istream& in, std::ostream& out) {
    int N;
    in >> N;
    vector<int> A(N);
    REP(i,0,N) in >> A[i];
    int minA = INT_MAX;
    int answer = 1;
    vector<int> mins;
    mins.emplace_back(A.back());
    RREP(i,0,N-1) {
        const auto itr = upper_bound(all(mins), A[i]);
        if (itr == mins.end()) {
            mins.emplace_back(A[i]);
            answer++;
        } else {
            *itr = A[i];
        }
    }
    out << answer << "\n";
}
};


int main() {
	ESequenceDecomposing solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
