/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;

class ESequenceDecomposing {
public:
	void solve(std::istream& in, std::ostream& out) {
	    int N;
	    in>>N;
	    multiset<int> S;
	    for(int i=0;i<N;i++){
	        int a;
	        in>>a;
	        auto itr = S.lower_bound(a);
	        if(itr==S.begin()) S.emplace(a);
	        else{
	            itr--;
	            S.erase(itr);
	            S.emplace(a);
	        }
	    }
	    out<<S.size()<<endl;
	}
};


int main() {
	ESequenceDecomposing solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
