/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author jcg
 */

#include <iostream>

#include <iostream>
#include <vector>
#include <algorithm>

class ESequenceDecomposing
{
public:
    void solve(std::istream& in, std::ostream& out)
    {
        int N;
        in >> N;

        std::vector<int> a;
        for (int i = 0; i < N; ++i)
        {
            int x;
            in >> x;
            if (a.empty() || a.back() >= x)
                a.emplace_back(x);
            else *std::upper_bound(a.begin(), a.end(), x, std::greater<int>()) = x;
        }
        out << a.size() << '\n';
    }
};


int main()
{
    std::ios_base::sync_with_stdio(0);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    in.tie(0);
    ESequenceDecomposing solver;
    solver.solve(in, out);
    return 0;
}
