/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Yulian
 */

#include <iostream>
#include <iostream>
#include <fstream>
#include <vector>
#include <set>
#include <cmath>
#include <queue>
#include <deque>
#include <string>
#include <algorithm>
#include <map>


#include <iostream>

#include <fstream>
#include <vector>
#include <set>
#include <cmath>
#include <queue>
#include <deque>
#include <string>
#include <algorithm>
#include <map>



int getTheAnswer() {
    return 42;
}

template< class InputIt>
void incAll(const InputIt &first, const InputIt &last){
  for(auto it = first; it != last; ++it){
    ++*it;
  }
}

template <class InputIt>
void printAll(const InputIt &first, const InputIt &last, std::ostream& out){
  for(InputIt it = first; it != last; ++it){
    out << *it << " ";
  }
}

// only for positive integers
int gcd(int a, int b){
  int tmp;
  if(a < b){
    tmp = a;
    a = b;
    b = tmp;
  }
  while(b != 0){
    tmp = a;
    a = b;
    b = tmp % b;
  }
  return a;
}

int lcm(int a, int b){
  return abs(a*b) / gcd(a, b);
}


using namespace std;
class TaskD {
public:
	void solve(std::istream& in, std::ostream& out) {
		ios::sync_with_stdio(false);
		int n;
		string s, res;
		in >> n >> s;
		res = s;
		vector<string> test(4, s);
		test[0][0] = 'S';
		test[0][1] = 'S';
		test[1][0] = 'W';
		test[1][1] = 'S';
		test[2][0] = 'S';
		test[2][1] = 'W';
		test[3][0] = 'W';
		test[3][1] = 'W';
		for (int j = 0; j < test.size(); ++j) {
			res = test[j];
			for (int i = 2; i < n; ++i) {
				if (res[i - 1] == 'S') {
					if (s[i - 1] == 'o') {
						res[i] = res[i - 2];
					} else {
						res[i] = res[i - 2] == 'S' ? 'W' : 'S';
					}
				} else {
					if (s[i - 1] == 'x') {
						res[i] = res[i - 2];
					} else {
						res[i] = res[i - 2] == 'S' ? 'W' : 'S';
					}
				}
			}
			if (res[n - 1] == 'S') {
				if (s[n - 1] == 'o' && res[n-2] != res[0] || s[n - 1] == 'x' && res[n-2] == res[0] ) {
					continue;
				}
			} else {
				if (s[n - 1] == 'x' && res[n-2] != res[0] || s[n - 1] == 'o' && res[n-2] == res[0] ) {
					continue;
				}
			}
			if (res[0] == 'S') {
				if (s[0] == 'o' && res[n-1] != res[1] || s[0] == 'x' && res[n-1] == res[1] ) {
					continue;
				}
			} else {
				if (s[0] == 'x' && res[n-1] != res[1] || s[0] == 'o' && res[n-1] == res[1] ) {
					continue;
				}
			}
			out << res << endl;
			return;
//			if (res[0] == 'S') {
//				if (s[0] == 'o') {
//					if (res[1] == res[n - 1]) {
//						out << res << endl;
//						return;
//					}
//				} else {
//					if (res[1] != res[n - 1]) {
//						out << res << endl;
//						return;
//					}
//				}
//			} else {
//				if (s[0] == 'x') {
//					if (res[1] == res[n - 1]) {
//						out << res << endl;
//						return;
//					}
//				} else {
//					if (res[1] != res[n - 1]) {
//						out << res << endl;
//						return;
//					}
//				}
//			}
		}
		out << "-1" << endl;
	}
};


int main() {
	TaskD solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
