/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define rep(i, n) for(ll i=0; i<n; i++)
#define repr(i, s, e) for(ll i=s; i>=e; i--)
#define reps(i, s, e) for(ll i=s; i<=e; i++)
#define inf 1e18
#define all(v) v.begin(),v.end()
#define ceill(a, b) (a+b-1)/b
#define ok cout << "ok" << endl;
#define sp << " " <<
void ans(bool b){ cout << (b ? "Yes" : "No") << endl; }
void ans2(bool b){ cout << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b) a=b; return a<b; }
template<typename T> inline bool chmin(T &a, T b){ if(b<a) a=b; return b<a; }
template<typename A, size_t N, typename T>
void Fill(A (&array)[N], const T &val){
    fill((T*)array, (T*)(array+N), val);
}
template<typename T> void vdeb(T v){
    cout << "#vector set debug" << endl;
    for(auto vv : v) cout << vv << " ";
    cout << endl;
}
template<typename T1, typename T2> void adeb(T1 arr[], T2 n){
    cout << "#adebug" << endl;
    for(int i=0; i<=n; i++) cout << arr[i] << " ";
    cout << endl;
}
template<typename T1> void mdeb(T1 mp){
    cout << "#map pair debug" << endl;
    for(auto const& m : mp) cout << m.first sp m.second << endl;
}
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};


class DMenagerie {
public:
	void solve(std::istream& in, std::ostream& out) {
        int n;
        string s;
        in >> n >> s;

        bool res = false;
        string t;
        for(int bit=0; bit < (1<<2); bit++){
            int l, r;
            t = "";
            rep(i, 2){
                if((1<<i) & bit) t += 'W';
                else t += 'S';
            }

            reps(i, 1, n-2){
                if(t[i] == 'S'){
                    if(s[i] == 'o') t += t[i-1];
                    else t += (t[i-1] == 'S') ? 'W' : 'S';
                }else if(t[i] == 'W'){
                    if(s[i] == 'o') t += (t[i-1] == 'S') ? 'W' : 'S';
                    else t += t[i-1];
                }
            }

            if(t[n-1] == 'S'){
                if(s[n-1] == 'o' && t[n-2] == t[0]) res = true;
                if(s[n-1] == 'x' && t[n-2] != t[0]) res = true;
            }else if(t[n-1] == 'W'){
                if(s[n-1] == 'o' && t[n-2] != t[0]) res = true;
                if(s[n-1] == 'x' && t[n-2] == t[0]) res = true;
            }

            if(t[0] == 'S'){
                if(s[0] == 'o' && t[n-1] != t[1]) res = false;
                if(s[0] == 'x' && t[n-1] == t[1]) res = false;
            }else if(t[0] == 'W'){
                if(s[0] == 'o' && t[n-1] == t[1]) res = false;
                if(s[0] == 'x' && t[n-1] != t[1]) res = false;
            }

            if(res) break;
        }

        if(res) out << t << endl;
        else out << -1 << endl;
	}
};


int main() {
	DMenagerie solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
