/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kamol Paul
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;
#define long long long
typedef pair < long , long > pii;
mt19937 rng(chrono::steady_clock::now().time_since_epoch().count());
class AStationAndBus {
public:
	void solve(std::istream& in, std::ostream& out) {
	    string data;
	    in>>data;
	    set<char> x;
	    for(char dd : data) x.insert(dd);
	    if(x.size()>1){
	        out<<"Yes";
	    }
	    else out<<"No";
	}
};


int main() {
    ios_base::sync_with_stdio(false);cin.tie(NULL);
	AStationAndBus solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
