#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S){
    if (S[0]=='A'&& S[1]=='A' && S[2]=='A') printf("No\n");
    else if (S[0]=='B'&& S[1]=='B' && S[2]=='B') printf("No\n");
    else printf("Yes\n");

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
