#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S)
{
    int ac = 0;
    int bc = 0;

    for(char c : S)
    {
        if(c == 'A')
        {
            ac++;
        }
        else if(c == 'B')
        {
            bc++;
        }
    }
    if(ac > 0 && bc > 0)
    {
        cout << YES << endl;
    }
    else
    {
        cout << NO << endl;
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
