#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S){
    int size = S.size();
    bool A=false;
    bool B=false;
    for(int i= 0;i<size;i++){
        if(S[i] == 'A'){
            A=true;
        }
        if(S[i]=='B'){
            B=true;
        }
    }
    if(A&&B){
        cout <<YES<<endl;
    }else{
        cout<<NO<<endl;
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
