/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Pranto
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
//#include<math.h>
//#include <algorithm>
#include <iostream>

int getTheAnswer() {
    return 42;
}
typedef struct node Node;

#define ll long long
#define maximum 1000000
#define q_size 100
using namespace std;


class Task {
public:

	void solve(std::istream& cin, std::ostream& cout) {

	   string s;
	   cin>>s;
	   ll numa=0,numb=0;
	   if(s[0]=='A') numa++;
	   else numb++;
        if(s[1]=='A') numa++;
        else numb++;
        if(s[2]=='A') numa++;
        else numb++;

        if(numa ==0 || numb==0) cout<<"No"<<endl;
        else cout<<"Yes\n";
    }
};


int main() {
	Task solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
