/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>
using namespace std;

class AStationAndBus {
 public:
  void solveOne(std::istream &in, std::ostream &out) {
    string s;
    in >> s;
    set<char> S;
    for (char c : s) S.insert(c);

    out << (S.size() == 2 ? "Yes" : "No") << endl;
  }
  void solve(std::istream &in, std::ostream &out) {
    int nt = 1;
    for (int i = 0; i < nt; ++i)
      solveOne(in, out);
  }
};

int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(NULL);
  AStationAndBus solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}