#include <bits/stdc++.h>
#define rep(i, n) for (int i = 0; i < (n); ++i)
using namespace std;
using ll = long long;
using P = pair<ll, ll>;

void solve(long long N, long long X, long long M) {
    ll ans = 0;
    unordered_map<int, int> mp;
    ll num = X;
    int i = 0;
    while (i < N) {
        // cerr << "num=" << num << endl;
        if (mp.find(num) != mp.end()) {
            ll loupLen = i - mp[num];
            ll remain = N - i;
            ll loupVal = 0;
            ll tempVal = num;
            rep(i, loupLen) {
                loupVal += tempVal;
                tempVal *= tempVal;
                tempVal %= M;
            }
            ll nextLoup = remain / loupLen;
            ans += loupVal * nextLoup;
            remain %= loupLen;
            tempVal = num;
            rep(i, remain) {
                ans += tempVal;
                tempVal *= tempVal;
                tempVal %= M;
            }
            break;
        } else {
            mp[num] = i;
            ans += num;
            num *= num;
            num %= M;
            i++;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
    long long N;
    scanf("%lld", &N);
    long long X;
    scanf("%lld", &X);
    long long M;
    scanf("%lld", &M);
    solve(N, X, M);
    return 0;
}
