/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Aman
 */


#include<bits/stdc++.h>

using namespace std;

#include <iostream>


#define ll   long long
#define pb          push_back

void __print(int x) { cout << x; }

void __print(long x) { cout << x; }

template<typename T, typename V>
void __print(const pair<T, V> &x) {
    cout << '{';
    __print(x.first);
    cout << ',';
    __print(x.second);
    cout << '}';
}

template<typename T>
void __print(const T &x) {
    int f = 0;
    cout << '{';
    for (auto &i: x) cout << (f++ ? "," : ""), __print(i);
    cout << "}";
}

void _print() { cout << "]\n"; }

template<typename T, typename... V>
void _print(T t, V... v) {
    __print(t);
    if (sizeof...(v)) cout << ", ";
    _print(v...);
}


#ifdef LOCAL
#else
#define dbg(x...)
#endif

ll m;

class ESequenceSum {
public:

    void solve2(std::istream &cin, std::ostream &cout) {
        ll n, x;
        cin >> n >> x >> m;
        map<ll, ll> prv;
        vector<ll> v;
        ll ans = 0, last, s = 0;
        for (ll i = 0;; i++) {
            last = i;
            if (prv.count(x)) break;
            prv[x] = i;
            v.pb(x);
            x = x * x % m;
        }
        n -= prv[x];

        for (ll i = 0; i < prv[x]; i++)
            ans += v[i];
        for (ll j = prv[x]; j < v.size(); j++)
            s += v[j];
        ans += (n / (last - prv[x])) * s;
        n %= (last - prv[x]);
        for (ll j = prv[x]; n > 0; n--, j++) {
            ans += v[j];
        }
        cout << ans;

    }

    void solve(std::istream &cin, std::ostream &cout) {
        ll t = 1;
//            cin >> t;
        while (t--) {
            solve2(cin, cout);
        }
    }

};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    ESequenceSum solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
