#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
const ll INF = 1e18;
const ll MOD = 1e9+7;
#define REP(i,j,n) for(int i=j;i<n;i++)
#define rep(i,n) REP(i,0,n)


// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    cin.tie(0);
    ios::sync_with_stdio(false);

    ll n,x,m;
    cin >> n >> x >> m;
    set<ll> st;
    set<ll> st2;
    ll ans = 0;
    ll nx = x;
    st.insert(nx);
    ll cnt=0;

    if (n<501010)
    {
        rep(i,n)
        {
            ans += nx;
            nx = (nx * nx ) % m;
        }
        cout << ans << endl;
        return 0;
    }


    rep(i,m+10)
    {
        cnt++;
        ans += nx;
        nx = (nx * nx) % m;
        auto itr = st.find(nx);
        if (itr!=st.end())
        {
            break;
        }
        st.insert(nx);
    }

    int loopcnt = 0;
    ll loopans = 0;
    int fx = nx;
    rep(j, m+10)
    {
        loopcnt++;
        st2.insert(nx);
        loopans += nx;
        nx = (nx * nx ) % m;
        auto itr = st2.find(nx);
        if (itr!=st2.end()) break;
    }
    ans += (n-cnt)/loopcnt * loopans;
    nx = fx;
    rep(i, (n-cnt)%loopcnt)
    {
        ans += nx;
        nx = (nx * nx ) % m;
    }
    cout << ans << endl;



}
