/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author aajisaka
 */


#include<bits/stdc++.h>

using namespace std;

void debug_out() { cerr << endl; }
template <typename Head, typename... Tail>
void debug_out(Head H, Tail... T) {
  cerr << " " << to_string(H);
  debug_out(T...);
}
#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

#define SPEED ios_base::sync_with_stdio(false);cin.tie(nullptr)
#define rep(i,n) for(int i=0; i<(int)(n); i++)
#define all(v) v.begin(), v.end()
template<class T> inline bool chmax(T& a, T b) { if (a < b) { a = b; return true; } return false; }
template<class T> inline bool chmin(T& a, T b) { if (a > b) { a = b; return true; } return false; }

using ll = long long;
using ull = unsigned long long;
using P = pair<ll, ll>;

constexpr long double PI = 3.14159265358979323846264338327950288L;
mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());

class ESequenceSum {
public:

    ll f(ll a, ll m) {
      return (a*a)%m;
    }

    void solve(istream& cin, ostream& cout) {
      SPEED;
      ll n, x, m; cin >> n >> x >> m;

      vector<vector<ll>> next(40, vector<ll>(m));
      vector<vector<ll>> dp(40, vector<ll>(m));
      rep(i, m) {
        dp[0][i] = i;
        next[0][i] = f(i, m);
      }

      for(int k=1; k<40; k++) {
        rep(i, m) {
          next[k][i] = next[k-1][next[k-1][i]];
          dp[k][i] = dp[k-1][i] + dp[k-1][next[k-1][i]];
        }
      }

      ll now = x;
      ll ret = 0;
      for(int k=0; k<40; k++) {
        if (n&(1LL<<k)) {
          ret += dp[k][now];
          now = next[k][now];
        }
      }

      cout << ret << endl;


    }
};

signed main() {
  ESequenceSum solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}