// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools

#include <bits/stdc++.h>
// #include "atcoder/all"

using namespace std;

using i64 = long long;

const i64 MOD = 1e9 + 7;
const i64 INF = i64(1e18) + 7;


template <typename T>
bool chmin(T& x, T y){
    if(x > y){
        x = y;
        return true;
    }
    return false;
}

template <typename T>
bool chmax(T& x, T y){
    if(x < y){
        x = y;
        return true;
    }
    return false;
}

// doc: https://shibh308.github.io/library/library/lib/classes/binarylifting.cpp.html
struct BinaryLifting{
    int n;
    vector<vector<int>> next;
    vector<int> par;
    vector<vector<int>> childs;
    vector<int> depth;

    BinaryLifting(vector<int> v) : n(v.size()){

        next.push_back(par);
        for(int k = 0;; ++k){
            bool fl = false;
            next.emplace_back(n, -1);
            for(int i = 0; i < n; ++i){
                next[k + 1][i] = (next[k][i] == -1 ? -1 : next[k][next[k][i]]);
                if(next[k + 1][i] != -1)
                    fl = true;
            }
            if(!fl)
                break;
        }
    }
    // kth_next(x, 0) => x
    int kth_next(int x, int k){
        for(int i = 0; i < next.size() && k; ++i){
            if(k & (1 << i)){
                x = next[i][x];
                if(x == -1)
                    break;
            }
        }
        return x;
    }
};

void solve(long long n, long long x, long long m){

    vector<vector<i64>> nex(1, vector<i64>(m));
    for(int i = 0; i < m; ++i)
        nex[0][i] = (1LL * i * i) % m;
    vector<vector<i64>> cost(1, vector<i64>(m));
    for(int i = 0; i < m; ++i)
        cost[0][i] = i;
    for(int i = 0; (1LL << i) <= n; ++i){
        nex.emplace_back(m, 0);
        cost.emplace_back(m, 0);
        for(int j = 0; j < m; ++j){
            nex[i + 1][j] = nex[i][nex[i][j]];
            cost[i + 1][j] = cost[i][j] + cost[i][nex[i][j]];
        }
    }
    i64 ans = 0;
    i64 now = x;
    for(int i = 0; i <= 60; ++i){
        if((1LL << i) & n){
            ans += cost[i][now];
            now = nex[i][now];
        }
    }
    cout << ans << endl;
}


signed main(){
    long long N;
    scanf("%lld",&N);
    long long X;
    scanf("%lld",&X);
    long long M;
    scanf("%lld",&M);
    solve(N, X, M);
    return 0;
}
