/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Pine1999
 */

#include <bits/stdc++.h>

using namespace std;

void ESequenceSum(std::istream& in, std::ostream& out) {
    long long n;
    in >> n;
    long long x, mod;
    in >> x >> mod;
    if (x == 1) {
        out << n << '\n';
        return;
    }
    if (x == 0) {
        out << 0 << '\n';
        return;
    }
    long long xx = x;
    long long ans = x;
    map<long long, int> mp;
    mp.insert({x, 1});
    int cur = 1;
    while (cur < n) {
        ++cur;
        xx *= xx;
        xx %= mod;
        //if (x == 10) cout << xx << '\n';
        if (mp.count(xx)) {
            // solve
            long long loop = cur - mp[xx];
            long long rest = n - cur + 1;
            long long loop_sum = xx;
            long long xxx = xx * xx % mod;
            while (xxx != xx) {
                loop_sum += xxx;
                xxx *= xxx;
                xxx %= mod;
            }
            ans += (rest / loop) * loop_sum;
            //ans %= mod;
            rest %= loop;
            //cout << rest << '\n';
            while (rest > 0) {
                rest--;
                ans += xx;
                xx *= xx;
                xx %= mod;
            }
            break;
        }
        ans += xx;
        //ans %= mod;
        mp.insert({xx, cur});
    }
    out << ans << '\n';
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    ESequenceSum(in, out);
    return 0;
}