/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author apurba_debnath
 */

#include <bits/stdc++.h>

#define ll long long
#define DEBUG(x) cout << '>' << #x << ':' << x << endl

using namespace std;

class AAirConditioner {
public:
    void solve(std::istream &in, std::ostream &out) {
        int t;
        in >> t;
        if (t >= 30)
            out << "Yes";
        else
            out << "No";
    }
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);

    AAirConditioner solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);

    return 0;
}
