/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yosiiii
 */


#include<bits/stdc++.h>
using namespace std;
#define rep(i,n) for(long long int i=0;i<(n);++i)
typedef long long int ll;

class AAirConditioner {
public:
	void solve(std::istream& in, std::ostream& out) {
        int x;
        in >> x;
        if(x>=30){
            out << "Yes" << endl;
        }else{
            out << "No" << endl;
        }
	}
};


int main() {
	AAirConditioner solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
