/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Hamadneh
 */

#include <bits/stdc++.h>

using namespace std;

class AAirConditioner {
public:
    void solve(istream &in, ostream &out) {
        int x;
        in >> x;
        if (x >= 30)
            out << "Yes";
        else
            out << "No";
    }
};


int main() {
    AAirConditioner solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
