#include <bits/stdc++.h>
using namespace std;


void solve(std::string c){
	if((c[0]=='a')||(c[0]=='i')||(c[0]=='u')||(c[0]=='e')||(c[0]=='o')){
		cout << "vowel" << endl;
	}else{
		cout << "consonant" << endl;
	}

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string c;
    std::cin >> c;
    solve(c);
    return 0;
}
