#include <bits/stdc++.h>
using namespace std;


void solve(std::string c){
  if (c[0] == 'a' or c[0] == 'e' or c[0] == 'i' or c[0] == 'o' or c[0] == 'u') {
      cout << "vowel" << endl;
  } else {
      cout << "consonant" << endl;
  }
}

// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string c;
    std::cin >> c;
    solve(c);
    return 0;
}
