#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> H){
    int ans=0;
    int maxH=H.at(0);
    for(int i=0; i<H.size(); i++) {
        if (maxH <= H.at(i)) {
            ans++;
            maxH = H.at(i);
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> H(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&H[i]);
    }
    solve(N, std::move(H));
    return 0;
}
