#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> H){
    int cnt = 0;
    int trueCnt = 0;
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < i; j++) {
            if (H[j] <= H[i]) {
                cnt++;
            }   
        } 
        if (cnt == i) trueCnt++; 
          
        cnt = 0;
    }   
    cout << trueCnt << endl;                                                                                     
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> H(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&H[i]);
    }
    solve(N, std::move(H));
    return 0;
}
