/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author TM
 */


#include <iostream>
#include <algorithm>
#include <vector>
#include <string>
#include <queue>
#include <map>
#include <set>
#include <functional>
#include <cmath>
#include <numeric>
#include <iterator>

#define SIZE 100005
#define MOD 1000000007
#define INF 100000000

using namespace std;

class COneStrokePath {
public:
    int dfs(int now, vector<bool> visited) {
        if (visited[now]) return 0;
        visited[now] = true;
        if (count(visited.begin(), visited.end(), false) == 1) {
            return 1;
        }
        int ans = 0;
        for (int i = 0; i < to_vec[now].size(); ++i) {
            ans += dfs(to_vec[now][i], visited);
        }
        return ans;

    }

    void solve(std::istream &cin, std::ostream &cout) {
        int n, m;
        cin >> n >> m;
        to_vec.resize(n + 1);
        vector<bool> visited(n + 1);

        for (int i = 0; i < m; ++i) {
            visited[i] = false;
            int a, b;
            cin >> a >> b;
            to_vec[a].push_back(b);
            to_vec[b].push_back(a);
        }
        cout << dfs(1, visited) << endl;
    }

    vector<vector<int>> to_vec;
};


int main() {
    COneStrokePath solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
