#include <bits/stdc++.h>
using namespace std;

bool isGood(vector<set<long long> > &G, vector<long long> &path){
    bool isValid = true;
    for(int i =0; i< path.size()-1; i++) {
        if(!G[path[i]].count(path[i+1])) isValid = false;
    }
    return isValid;
}

void solve(long long N, long long M, std::vector<long long> a, std::vector<long long> b){
    vector<set<long long> > G(N);
    vector<long long> path(N);
    for(int i=0; i< M; i++){
        G[a[i]-1].insert(b[i]-1);
        G[b[i]-1].insert(a[i]-1);
    }
    for(int i=0; i< N; i++){
        path[i] = i;
    }
    long long count = 0;
    do{
        if(isGood(G, path)) count ++;
    } while (next_permutation(path.begin()+1, path.end()));
    cout << count << endl;

}

// Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> a(M);
    std::vector<long long> b(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&a[i]);
        scanf("%lld",&b[i]);
    }
    solve(N, M, std::move(a), std::move(b));
    return 0;
}
