/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Yulian
 */

#include <iostream>
#include <iostream>
#include <fstream>
#include <vector>
#include <set>
#include <cmath>
#include <queue>
#include <deque>
#include <string>
#include <algorithm>
#include <map>


#include <iostream>

#include <fstream>
#include <vector>
#include <set>
#include <cmath>
#include <queue>
#include <deque>
#include <string>
#include <algorithm>
#include <map>
//#include "../../library/lib.hpp"


using namespace std;

class TaskC {
public:
public:
  void dfs(int i, set<int> visited, const vector<set<int>> &a, vector<set<int>> &result) {
    visited.insert(i);
    bool end = true;
    if (visited.size() == a.size()) {
      end = true;
    } else {
      for (auto it = a[i].begin(); it != a[i].end(); ++it) {
        if (visited.find(*it) == visited.end()) {
          dfs(*it, visited, a, result);
          end = false;
        }
      }
    }
    if (end) {
      result.push_back(visited);
    }
  }

  void solve(std::istream &in, std::ostream &out) {
    ios::sync_with_stdio(false);
    int n, m, x, y;
    in >> n >> m;
    vector<set<int>> a(n + 1);
    for (int i = 0; i < m; ++i) {
      in >> x >> y;
      a[x].insert(y);
      a[y].insert(x);
    }
    vector<set<int>> result;
    dfs(1, {}, a, result);

    int cnt = 0;
    for (auto &path : result) {
      if (path.size() == n) {
        ++cnt;
//        tmp.clear();
//        for (auto &el : path) {
//          tmp.insert(el);
//        }
//        if (tmp.size() == n) {
//          ++cnt;
//        }
      }
    }
    out << cnt << endl;
  }
};


int main() {
	TaskC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
