/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author TM
 */


#include <bits/stdc++.h>

using namespace std;

class CHalfAndHalf {
public:
  void solve(std::istream &cin, std::ostream &cout) {
    int64_t a, b, c, x, y;
    cin >> a >> b >> c >> x >> y;
    int64_t two_a = min(a, 2 * c);
    int64_t two_b = min(b, 2 * c);
    cout << min({a * x + b * y, 2 * c * max(x, y), 2 * c * min(x, y) + abs(x - y) * (x > y ? a : b)}) << endl;
  }
};


int main() {
  CHalfAndHalf solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
