#!/usr/bin/env python3



# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H , W = map(int,input().split())

    A = []
    for i in range(H):
        A.append(list(input()))

    B = list(zip(*A))

    AA = []
    for a in A:
        AA.append(all(x == "." for x in a))

    BA = []
    for b in B:
        BA.append(all(x == "." for x in b))

    for a,aa in zip(A,AA):
        if not aa:
            for b,ba in zip(a,BA):
                if not ba:
                    print(b,end="")
            print("")




    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
