#!/usr/bin/env python3
ans_index = []

def get_index(s):
    a = ""
    for ans in ans_index:
        a += s[ans]
    return a

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    A = []
    for _ in range(H):
        s = input()
        if s != "." * W:
            A.append(s)

    for w in range(W):
        add = True
        for h in range(len(A)):
            if A[h][w] != ".":
                add = False
                break
        if not add:
            ans_index.append(w)

    #print(A, ans_index)

    for line in map(get_index, A):
        print("".join(line))
    return

if __name__ == '__main__':
    main()
