#!/usr/bin/env python3
from itertools import *

# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H , W = map(int,input().split())

    A = [list(input()) for i in range(H)]
    B = list(zip(*A))

    AA = [not all(x=="." for x in a) for a in A]
    BA = [not all(x=="." for x in b) for b in B]

    for a in compress(A,AA):
        for b in compress(a,BA):
            print(b,end="")
        print("")

    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
