/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author champon
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define ok cout << "ok" << endl;
#define sp << " " <<
using namespace std;
typedef long long ll;
const ll mod = 1e9+7;
const ll inf = 9e18;
template<typename T1, typename T2> ll ceill(T1 a, T2 b){ return (a+b-1)/b; }
void ans(bool b, ostream& out=cout){ out << (b ? "Yes" : "No") << endl; }
void ans2(bool b, ostream& out=cout){ out << (b ? "YES" : "NO") << endl; }
template<typename T> inline bool chmax(T &a, T b){ if(a<b){a=b; return true;} return false; }
template<typename T> inline bool chmin(T &a, T b){ if(a>b){a=b; return true;} return false; }
template<typename A, size_t N, typename T> void Fill(A (&array)[N], const T &val){fill((T*)array, (T*)(array+N), val);}
int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
int dy[] = {0, 1, 0, -1, 1, -1, -1, 1};

#ifndef INCLUDE_DEBUG_HPP
#define INCLUDE_DEBUG_HPP

#include <iostream>
#include <vector>
#include <map>
using namespace std;

class debug
{
public:
    typedef long long ll;
    template<typename T> void vd(vector<T> vec);
    template<typename T> void vd2(vector<vector<T>> vec);
    template<typename T> void vpd(vector<pair<int, int>> vec);
    template<typename T> void ad(T *arr, ll n);
    template<typename T, size_t N> void ad2(T (&arr)[N], ll n);
    template<typename T> void md(T mp);
};

#endif //INCLUDE_DEBUG_HPP

template<typename T> void debug::vd(vector<T> vec)
{
    for(auto vv : vec) cout << vv << " ";
    cout << endl;
}

template<typename T> void debug::vd2(vector<vector<T>> vec)
{
    for(auto vv : vec) for(auto vvv : vv) cout << vvv << " ";
    cout << endl;
}

template<typename T> void debug::vpd(vector<pair<int, int>> vec) {
    for(auto const& vv : vec) {
        cout << vv.first << " " << vv.second << endl;
    }
    cout << endl;
}

template<typename T> void debug::ad(T *arr, ll n)
{
    for(int i=0; i<=n; i++) cout << arr[i] << " ";
    cout << endl;
}

template<typename T, size_t N> void debug::ad2(T (&arr)[N], ll n)
{
    for(int i=0; i<=N; i++) for(int j=0; j<=n; j++) cout << arr[i][j] << " ";
    cout << endl;
}

template<typename T> void debug::md(T mp)
{
    cout << "key : value" << endl;
    for(auto const& m : mp) cout << m.first << " : " << m.second << endl;
    cout << endl;
}
debug debug;

#ifndef DEFINE_COMBINATION_HPP
#define DEFINE_COMBINATION_HPP


using namespace std;

template<typename T>
class Comb
{
    typedef long long ll;
    ll mod = 1e9+7;
  public:
    vector<vector<T>> comb;
    vector<T> fact;
    vector<T> finv;
    vector<T> inv;
    Comb(){};
    Comb(int n) { build(n); }

    void build(int n);
    T result(int n, int k); // return nCk
};

#endif //DEFINE_COMBINATION_HPP

template<typename T>
void Comb<T>::build(int n)
{
    inv.assign(n+1, 0);
    fact.assign(n+1, 0);
    finv.assign(n+1, 0);
    fact[0] = fact[1] = finv[0] = finv[1] = 1;
    inv[1] = 1;
    for(int i=2; i<=n; i++){
        fact[i] = fact[i-1]*i % mod;
        inv[i] = mod - inv[mod%i]*(mod/i)%mod;
        finv[i] = finv[i-1]*inv[i]%mod;
    }
}

template<typename T>
T Comb<T>::result(int n, int k)
{
    if(n < k) return 0;
    if(n < 0 || k < 0) return 0;
    return fact[n]*(finv[k]*finv[n-k]%mod)%mod;
}

// verify
// https://atcoder.jp/contests/abc034/tasks/abc034_c


class EAlmostEverywhereZero {
public:
	void solve(std::istream& in, std::ostream& out)
	{
        string n;
        int K;
        in >> n >> K;

        int len = n.length();
        vector<vector<vector<int>>> dp(110, vector<vector<int>>(4, vector<int>(2, 0)));
        dp[0][0][0] = 1;
        for(int i=0; i<len; i++){
            for(int j=0; j<=3; j++){
                for(int k=0; k<2; k++){
                    int nd = n[i]-'0';
                    for(int d=0; d<10; d++){
                        int ni = i+1, nj = j, nk = k;
                        if(d != 0) nj++;
                        if(nj > K) continue;
                        if(k == 0) {
                            if(d > nd) continue;
                            if(d < nd) nk = 1;
                        }
                        dp[ni][nj][nk] += dp[i][j][k];
                    }
                }
            }
        }

        out << dp[len][K][0] + dp[len][K][1] << endl;
	}
};


int main() {
	EAlmostEverywhereZero solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
