#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

std::vector<std::vector<long long>>  ncr;

std::vector<std::vector<long long>> comb(int n, int r) {
  std::vector<std::vector<long long>> v(n + 1,std::vector<long long>(n + 1, 0));
  for (int i = 0; i < v.size(); i++) {
    v[i][0] = 1;
    v[i][i] = 1;
  }
  for (int j = 1; j < v.size(); j++) {
    for (int k = 1; k < j; k++) {
      v[j][k] = (v[j - 1][k - 1] + v[j - 1][k]);
    }
  }
  return v;
}


ll solver(string&N,ll K){
    if (N.size() == 1){
        if (K ==1) return atoi(N.substr(0,1).c_str());
        else return 0;
    }else if (K == 0){
        return 1;
    }
    else{
        int n = atoi(N.substr(0,1).c_str());
        int keta = N.size();
        if (n == 0){
            string new_str = N.substr(1);
            return solver(new_str,K);
        }else{
            ll kjou = 1;
            for (int i=0;i<K;i++){
                kjou *= 9;
            }
            string new_str = N.substr(1);
            return (n-1) * ncr[keta-1][K-1] * kjou/9  + solver(new_str,K-1) + ncr[keta-1][K] *kjou ;
        }
    }
     
}

void solve(string N, long long K){
    ll ans = solver(N,K);
    printf("%lld\n",ans);

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    string N;
    cin >> N;
    long long K;
    ncr = comb(N.size(),K);

    scanf("%lld",&K);
    solve(N, K);
    return 0;
}
