// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools

#include <bits/stdc++.h>

using namespace std;

using i64 = long long;

const i64 MOD = 1e9 + 7;
const i64 INF = i64(1e18) + 7;


template <typename T>
bool chmin(T& x, T y){
    if(x > y){
        x = y;
        return true;
    }
    return false;
}

template <typename T>
bool chmax(T& x, T y){
    if(x < y){
        x = y;
        return true;
    }
    return false;
}


void solve(string s, long long k){
    int n = s.size();
    int p = 1;
    int q = 1;
    for(int i = 0; i < k; ++i)
        p *= n;
    for(int i = 0; i < k; ++i)
        q *= 9;

    string t;
    for(int i = 0; i < n; ++i)
        t += '0';

    i64 ans = 0;
    for(int mask = 0; mask < p; ++mask){
        vector<int> pos;
        int j = mask;
        for(int i = 0; i < k; ++i){
            int x = j % n;
            pos.emplace_back(x);
            j /= n;
        }
        bool fl = true;
        for(int i = 0; i < pos.size() - 1; ++i)
            fl &= pos[i] > pos[i + 1];
        if(!fl)
            continue;

        auto f = [&](int val){
            for(int i = 0; i < k; ++i){
                int vv = val % 9;
                t[pos[i]] = vv + '1';
                val /= 9;
            }
            bool fl = (s >= t);
            for(int i = 0; i < k; ++i)
                t[pos[i]] = '0';
            return fl;
        };

        int ok = -1, ng = q;
        while(ng - ok > 1){
            int mid = (ok + ng) / 2;
            (f(mid) ? ok : ng) = mid;
        }
        ans += ok + 1;
    }
    cout << ans << endl;
}


signed main(){
    string s;
    cin >> s;
    long long K;
    scanf("%lld",&K);
    solve(s, K);
    return 0;
}
