/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include "bits/stdc++.h"

using namespace std;

typedef unsigned long long ll;
typedef int                     integer;
#define int                     long long
#define ii                      pair<int,int>
#define vii                     vector<pair<int,int>>
#define vi                      vector<int>
#define vvi                     vector<vector<int>>
#define f(a,b,c)                for(int a=b;a<c;a++)
#define s(x)                    in>>x
#define s2(x,y)                 in>>x>>y
#define s3(x,y,z)               in>>x>>y>>z
#define s4(x,y,z,w)             in>>x>>y>>z>>w
#define p(x)                    out<<x<<endl
#define p2(x,y)                 out<<x<<" "<<y<<endl
#define pl(x)                   out<<x
#define p2l(x,y)                out<<x<<" "<<y
#define p1d(a,n)                for(int ix=0;ix<n;ix++) out<<a[ix]<<" "; out<<endl
#define p2d(a,n,m)              for(int ix=0;ix<n;ix++){ for(int jx=0;jx<m;jx++) out<<a[ix][jx]<<" "; out<<endl;}
#define range(v)                v.begin(),v.end()
#define w(x)                    while(x--)
#define rst(x)                  memset(x, -1, sizeof(x))
#define UNVISITED               -1
#define VISITED                 0
#define EXPLORED                2

int count(int n, int k){
    int ans= 1;
    if(n < 0) return 0;
    if(k>n)
        return 0;
    f(i,0,k){
        ans*=(n-i);
    }
    f(i,0,k){
        ans/=(i+1);
    }
    return ans*pow(9,k);
}

int count_last(string n, int k){
    int used = 0;
    int ans = 0;
    int tt = 0;
    f(i,0,n.size()){
        if(used == k) break;
        if(i == 0){
        if(n[i] != '0'){ used++;
        ans+= (n[i]-'1')*count(n.size()-i-1, k-used);
        }}
        if(i>=1){
            if(n[i] != '0'){
                ans+= count(n.size()-i-1, k-used);
                used++;
                ans+= (n[i]-'1')*count(n.size()-i-1, k-used);

            }else{
                tt++;
            }
        }

    }
    if(used == k) ans++;
    return ans;
}

int ssolve(string n, int k){
    int ans = count(n.size()-1, k);
    ans+= count_last(n, k);
    return ans;
}

int nonz(int i){
    int r = 0;
    while(i!=0){
        if(i%10 != 0)r++;
        i/=10;
    }
    return r;
}

int count_natora(int n, int k){
    int c = 0;
    f(i,1,n+1){
        if(nonz(i) == k) c++;
    }
    return c;
}
class EAlmostEverywhereZero {
public:
	void solve(std::istream& in, std::ostream& out) {
        string n;
        s(n);
        int k;
        s(k);

        out<<ssolve(n,k)<<endl;

	}
};


integer main() {
	EAlmostEverywhereZero solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
}
