#include <bits/stdc++.h>
using namespace std;

typedef long long ll; // -9,223,372,036,854,775,808 から 9,223,372,036,854,775,807

template <class T> using vec = std::vector<T>;
template <class T> using vec2 = vec<vec<T>>;
template <class T> using vec3 = vec<vec<vec<T>>>;

#define DEBUG

ll comb(ll n, ll k){
    if(k == 3){
        return n*(n-1)*(n-2)/6;
    }else if(k == 2){
        return n*(n-1)/2;
    }else if(k == 1){
        return n;
    }else if(k == 0){
        return 1;
    }
    cout << k << endl;
    assert(0);
}

ll makeFree(ll Ndigit, ll K){
    if(K < 0){
        return 0;
    }
    if(K > Ndigit){
        return 0;
    }
    return pow(9, K)*comb(Ndigit, K);
}

ll rec(vec<int>& digits, int ptr, ll K){
    if(ptr == digits.size() - 1){
        if(K == 0){
            // そこは0
            return 1;
        }else if(K == 1){
            // そこは非0
            return digits.back();
        }else{
            // K個も非0をつくれない。条件をみたさない。
            return 0;
        }
    }
    ll res = 0;
    ll NdigitsFol = digits.size() - ptr - 1;
    if(digits.at(ptr) == 0){
        // なんでもいいのでこの下の桁で非0をK個つくるやりかた
        res += rec(digits, ptr+1, K);
    }else{
        // この桁は維持する
        res += rec(digits, ptr+1, K-1);
        // この桁を非0で小さくする
        res += (digits.at(ptr) - 1)*makeFree(NdigitsFol, K - 1);
        // この桁を0にする
        res += makeFree(NdigitsFol, K);
    }

    return res;
    
}

void solve(string N, long long K){
    vec<int> digits;
    for(auto iter: (N)){
        digits.push_back(iter - '0');
    }

    cout << rec(digits, 0, K) << endl;

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    // long long N;
    // scanf("%lld",&N);
    string N;
    cin >> N;
    long long K;
    scanf("%lld",&K);
    solve(N, K);
    return 0;
}
